"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.OrderedEnumeration.SeaStateEnumModule
  IDL file: OrderedEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class SeaStateEnumType(idl.IdlEnum, typename="UMAA.Common.OrderedEnumeration.SeaStateEnumModule.SeaStateEnumType", default="CALM_GLOSSY"):
    CALM_GLOSSY = auto()
    CALM_RIPPLED = auto()
    HIGH = auto()
    MODERATE = auto()
    PHENOMENAL = auto()
    ROUGH = auto()
    SLIGHT = auto()
    SMOOTH = auto()
    VERY_HIGH = auto()
    VERY_ROUGH = auto()

