"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.PathReporterStatus
  IDL file: PathReporterReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.MM.BaseType


PathReporterReportTypeTopic = "UMAA::SA::PathReporterStatus::PathReporterReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PathReporterReportType(idl.IdlStruct, typename="UMAA.SA.PathReporterStatus.PathReporterReportType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    historicalGlobalPathsListMetadata: 'UMAA.Common.LargeListMetadata'
    historicalLocalPathsListMetadata: 'UMAA.Common.LargeListMetadata'
    plannedGlobalPathsListMetadata: 'UMAA.Common.LargeListMetadata'
    plannedLocalPathsListMetadata: 'UMAA.Common.LargeListMetadata'

PathReporterReportTypeHistoricalGlobalPathsListElementTopic = "UMAA::SA::PathReporterStatus::PathReporterReportTypeHistoricalGlobalPathsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PathReporterReportTypeHistoricalGlobalPathsListElement(idl.IdlStruct, typename="UMAA.SA.PathReporterStatus.PathReporterReportTypeHistoricalGlobalPathsListElement"):
    element: 'UMAA.MM.BaseType.WaypointType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']

PathReporterReportTypeHistoricalLocalPathsListElementTopic = "UMAA::SA::PathReporterStatus::PathReporterReportTypeHistoricalLocalPathsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PathReporterReportTypeHistoricalLocalPathsListElement(idl.IdlStruct, typename="UMAA.SA.PathReporterStatus.PathReporterReportTypeHistoricalLocalPathsListElement"):
    element: 'UMAA.MM.BaseType.WaypointType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']

PathReporterReportTypePlannedGlobalPathsListElementTopic = "UMAA::SA::PathReporterStatus::PathReporterReportTypePlannedGlobalPathsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PathReporterReportTypePlannedGlobalPathsListElement(idl.IdlStruct, typename="UMAA.SA.PathReporterStatus.PathReporterReportTypePlannedGlobalPathsListElement"):
    element: 'UMAA.MM.BaseType.WaypointType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']

PathReporterReportTypePlannedLocalPathsListElementTopic = "UMAA::SA::PathReporterStatus::PathReporterReportTypePlannedLocalPathsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PathReporterReportTypePlannedLocalPathsListElement(idl.IdlStruct, typename="UMAA.SA.PathReporterStatus.PathReporterReportTypePlannedLocalPathsListElement"):
    element: 'UMAA.MM.BaseType.WaypointType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']


