"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ProcessingUnitStatus

"""

from ._ProcessingUnitReportType import ProcessingUnitReportType, ProcessingUnitReportTypeTopic
__all__ = [
	"ProcessingUnitReportType",
	"ProcessingUnitReportTypeTopic",
]
