"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ProcessingUnitStatus
  IDL file: ProcessingUnitReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.ProcessingUnitEnumModule
    import UMAA.Common.Measurement


ProcessingUnitReportTypeTopic = "UMAA::SO::ProcessingUnitStatus::ProcessingUnitReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ProcessingUnitReportType(idl.IdlStruct, typename="UMAA.SO.ProcessingUnitStatus.ProcessingUnitReportType"):
    load15MinuteAverage: Optional['UMAA.Common.Measurement.Percent']
    load1MinuteAverage: Optional['UMAA.Common.Measurement.Percent']
    load5MinuteAverage: Optional['UMAA.Common.Measurement.Percent']
    numberOfBlockedProcesses: Optional['UMAA.Common.Measurement.Count']
    numberOfProcesses: Optional['UMAA.Common.Measurement.Count']
    numberOfRunningProcesses: Optional['UMAA.Common.Measurement.Count']
    processorTemperature: Optional['UMAA.Common.Measurement.Temperature']
    type: 'UMAA.Common.MaritimeEnumeration.ProcessingUnitEnumModule.ProcessingUnitEnumType'
    uptime: Optional['UMAA.Common.Measurement.DurationSeconds']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


