"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.AnchorLocationEnumModule

"""

from ._MaritimeEnumerationSets import AnchorLocationEnumType
__all__ = [
	"AnchorLocationEnumType",
]
