"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.HeadingSectorKindEnumModule

"""

from ._MaritimeEnumerationSets import HeadingSectorKindEnumType
__all__ = [
	"HeadingSectorKindEnumType",
]
