"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.FinsStatus
  IDL file: FinsStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class FinsStatusType(idl.IdlStruct, typename="UMAA.EO.FinsStatus.FinsStatusType"):
    fins: types.sequence['UMAA.EO.FinsStatus.FinStatusType', 16]


