"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.MapSegmentControl
  IDL file: MapSegmentCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


MapSegmentCommandTypeTopic = "UMAA::SEM::MapSegmentControl::MapSegmentCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MapSegmentCommandType(idl.IdlStruct, typename="UMAA.SEM.MapSegmentControl.MapSegmentCommandType"):
    segment: 'UMAA.Common.Measurement.SegmentID'
    survey: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


