"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.MapSegmentControl
  IDL file: MapSegmentCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


MapSegmentCommandAckReportTypeTopic = "UMAA::SEM::MapSegmentControl::MapSegmentCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MapSegmentCommandAckReportType(idl.IdlStruct, typename="UMAA.SEM.MapSegmentControl.MapSegmentCommandAckReportType"):
    command: 'UMAA.SEM.MapSegmentControl.MapSegmentCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


