"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ObjectiveAssignmentControl
  IDL file: ObjectiveAssignmentCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


ObjectiveAssignmentCommandAckReportTypeTopic = "UMAA::MM::ObjectiveAssignmentControl::ObjectiveAssignmentCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ObjectiveAssignmentCommandAckReportType(idl.IdlStruct, typename="UMAA.MM.ObjectiveAssignmentControl.ObjectiveAssignmentCommandAckReportType"):
    command: 'UMAA.MM.ObjectiveAssignmentControl.ObjectiveAssignmentCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


