"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ContactManeuverInfluenceEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ContactManeuverInfluenceEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ContactManeuverInfluenceEnumModule.ContactManeuverInfluenceEnumType", default="COLLISION"):
    COLLISION = auto()
    COLLISION_AVOIDANCE = auto()
    CROSSING_LEFT_COMPLIANT = auto()
    CROSSING_LEFT_NONCOMPLIANT = auto()
    CROSSING_RIGHT_COMPLIANT = auto()
    CROSSING_RIGHT_NONCOMPLIANT = auto()
    DYNAMIC_AVOIDANCE = auto()
    GUIDE = auto()
    HEAD_ON_COMPLIANT = auto()
    HEAD_ON_NONCOMPLIANT = auto()
    NONE = auto()
    OVERTAKEN_COMPLIANT = auto()
    OVERTAKEN_NONCOMPLIANT = auto()
    OVERTAKING_COMPLIANT = auto()
    OVERTAKING_NONCOMPLIANT = auto()
    PREEMPTIVE = auto()
    STATIC_AVOIDANCE = auto()

