"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common
  IDL file: LargeListMetadata.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
class LargeListMetadata(idl.IdlStruct, typename="UMAA.Common.LargeListMetadata"):
    listID: 'UMAA.Common.Measurement.NumericGUID'
    updateElementID: 'UMAA.Common.Measurement.NumericGUID'
    updateElementTimestamp: Optional['UMAA.Common.Measurement.DateTime']
    startingElementID: 'UMAA.Common.Measurement.NumericGUID'
    size: types.int32


