"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.CommandStatusReasonEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class CommandStatusReasonEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.CommandStatusReasonEnumModule.CommandStatusReasonEnumType", default="CANCELED"):
    CANCELED = auto()
    INTERRUPTED = auto()
    OBJECTIVE_FAILED = auto()
    RESOURCE_FAILED = auto()
    RESOURCE_REJECTED = auto()
    SERVICE_FAILED = auto()
    SUCCEEDED = auto()
    TIMEOUT = auto()
    UPDATED = auto()
    VALIDATION_FAILED = auto()

