"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.TrackCategoryEnumModule

"""

from ._MaritimeEnumerationSets import TrackCategoryEnumType
__all__ = [
	"TrackCategoryEnumType",
]
