"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactCategoryReport
  IDL file: ContactCategoryReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.TrackCategoryEnumModule
    import UMAA.Common.Measurement


ContactCategoryReportTypeTopic = "UMAA::SA::ContactCategoryReport::ContactCategoryReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactCategoryReportType(idl.IdlStruct, typename="UMAA.SA.ContactCategoryReport.ContactCategoryReportType"):
    confidence: 'UMAA.Common.Measurement.Percent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    category: 'UMAA.Common.MaritimeEnumeration.TrackCategoryEnumModule.TrackCategoryEnumType'
    annotate.key("category")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")


