"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.MissionPlanMissionControl
  IDL file: MissionPlanMissionDeleteCommandStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.CommandStatusEnumModule
    import UMAA.Common.MaritimeEnumeration.CommandStatusReasonEnumModule
    import UMAA.Common.Measurement


MissionPlanMissionDeleteCommandStatusTypeTopic = "UMAA::MM::MissionPlanMissionControl::MissionPlanMissionDeleteCommandStatusType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanMissionDeleteCommandStatusType(idl.IdlStruct, typename="UMAA.MM.MissionPlanMissionControl.MissionPlanMissionDeleteCommandStatusType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    commandStatus: 'UMAA.Common.MaritimeEnumeration.CommandStatusEnumModule.CommandStatusEnumType'
    commandStatusReason: 'UMAA.Common.MaritimeEnumeration.CommandStatusReasonEnumModule.CommandStatusReasonEnumType'
    logMessage: types.bounded_str[4095]


