"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.OrderedEnumeration.WeatherSeverityEnumModule

"""

from ._OrderedEnumerationSets import WeatherSeverityEnumType
__all__ = [
	"WeatherSeverityEnumType",
]
