"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.SoundVelocityProfileReport
  IDL file: SoundVelocityProfileReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Environment
    import UMAA.Common.Measurement


SoundVelocityProfileReportTypeTopic = "UMAA::SA::SoundVelocityProfileReport::SoundVelocityProfileReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class SoundVelocityProfileReportType(idl.IdlStruct, typename="UMAA.SA.SoundVelocityProfileReport.SoundVelocityProfileReportType"):
    soundSpeed: types.sequence['UMAA.Common.Environment.DepthSpeedPairType', 1024]
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


