"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.GeneratorStatus
  IDL file: GeneratorReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.PowerPlantStateEnumModule
    import UMAA.Common.Measurement


GeneratorReportTypeTopic = "UMAA::EO::GeneratorStatus::GeneratorReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GeneratorReportType(idl.IdlStruct, typename="UMAA.EO.GeneratorStatus.GeneratorReportType"):
    current: 'UMAA.Common.Measurement.PowerBusCurrent'
    state: 'UMAA.Common.MaritimeEnumeration.PowerPlantStateEnumModule.PowerPlantStateEnumType'
    voltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


