"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Angle
  IDL file: PropellerPitchAnglePropulsorRequirementType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PropellerPitchAnglePropulsorRequirementType(idl.IdlStruct, typename="UMAA.Common.Angle.PropellerPitchAnglePropulsorRequirementType"):
    propellerPitchAnglePropulsor: 'UMAA.Common.Measurement.PropellerPitchAnglePropulsor'
    propellerPitchAnglePropulsorTolerance: Optional['UMAA.Common.Angle.PropellerPitchAnglePropulsorToleranceType']


