"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalVectorControl
  IDL file: GlobalVectorCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.DirectionModeEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.Speed


GlobalVectorCommandTypeTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalVectorCommandType(idl.IdlStruct, typename="UMAA.MO.GlobalVectorControl.GlobalVectorCommandType"):
    depthChangePitch: Optional['UMAA.Common.Orientation.PitchYNEDRequirement']
    direction: 'UMAA.Common.Orientation.DirectionRequirementVariantType'
    directionMode: 'UMAA.Common.MaritimeEnumeration.DirectionModeEnumModule.DirectionModeEnumType'
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    endTime: Optional['UMAA.Common.Measurement.DateTime']
    speed: 'UMAA.Common.Speed.SpeedRequirementVariantType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


