"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalVectorControl
  IDL file: GlobalVectorExecutionStatusReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


GlobalVectorExecutionStatusReportTypeTopic = "UMAA::MO::GlobalVectorControl::GlobalVectorExecutionStatusReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalVectorExecutionStatusReportType(idl.IdlStruct, typename="UMAA.MO.GlobalVectorControl.GlobalVectorExecutionStatusReportType"):
    directionAchieved: bool
    elevationAchieved: bool
    speedAchieved: bool
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


