"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.BaseType
  IDL file: FLSConfigSearchBottomType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class FLSConfigSearchBottomType(idl.IdlStruct, typename="UMAA.SEM.BaseType.FLSConfigSearchBottomType"):
    goalVehicleAltitude: 'UMAA.Common.Measurement.DistanceASF'
    goalVehicleDepth: 'UMAA.Common.Measurement.DistanceBSL'
    maxRange: 'UMAA.Common.Measurement.Distance'
    minRange: Optional['UMAA.Common.Measurement.Distance']


