"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.BaseType
  IDL file: FLSConfigTestType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.FLSBeamwidthEnumModule
    import UMAA.Common.MaritimeEnumeration.FLSWaveformLengthEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.MeasurementConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class FLSConfigTestType(idl.IdlStruct, typename="UMAA.SEM.BaseType.FLSConfigTestType"):
    activeBandwidth: 'UMAA.Common.Measurement.FrequencyHertz'
    activeCenterFrequency: 'UMAA.Common.Measurement.FrequencyHertz'
    attenuation: 'UMAA.Common.Measurement.TransmitAttenuation'
    beamwidth: 'UMAA.Common.MaritimeEnumeration.FLSBeamwidthEnumModule.FLSBeamwidthEnumType'
    passiveBandwidth: 'UMAA.Common.Measurement.FrequencyHertz'
    passiveCenterFrequency: 'UMAA.Common.Measurement.FrequencyHertz'
    range: 'UMAA.Common.Measurement.Distance'
    steering: 'UMAA.Common.MeasurementConstrained.AngleHalf'
    upSweep: bool
    waveformLength: 'UMAA.Common.MaritimeEnumeration.FLSWaveformLengthEnumModule.FLSWaveformLengthEnumType'


