"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.StillImageStatus

"""

from ._StillImageReportType import StillImageReportType, StillImageReportTypeTopic
__all__ = [
	"StillImageReportType",
	"StillImageReportTypeTopic",
]
