"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.StillImageStatus
  IDL file: StillImageReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Environment
    import UMAA.Common.MaritimeEnumeration.ImageFormatEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


StillImageReportTypeTopic = "UMAA::SA::StillImageStatus::StillImageReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class StillImageReportType(idl.IdlStruct, typename="UMAA.SA.StillImageStatus.StillImageReportType"):
    altitudeAGL: Optional['UMAA.Common.Measurement.DistanceAGL']
    altitudeASF: Optional['UMAA.Common.Measurement.DistanceASF']
    altitudeGeodetic: Optional['UMAA.Common.PrimitiveConstrained.GeodeticAltitude']
    altitudeMSL: Optional['UMAA.Common.Measurement.MSLAltitude']
    depth: Optional['UMAA.Common.Measurement.DistanceBSL']
    imageFormat: 'UMAA.Common.MaritimeEnumeration.ImageFormatEnumModule.ImageFormatEnumType'
    imageName: Optional['UMAA.Common.PrimitiveConstrained.StringShortDescription']
    imageURI: 'UMAA.Common.PrimitiveConstrained.UniformResourceIdentifier'
    position: Optional['UMAA.Common.Measurement.GeoPosition3DWGS84']
    transform: Optional['UMAA.Common.Environment.WorldTransformType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")
    imageID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("imageID")


