"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.PropulsorsStatus
  IDL file: PropulsorStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PropulsorStatusType(idl.IdlStruct, typename="UMAA.EO.PropulsorsStatus.PropulsorStatusType"):
    gamma: Optional['UMAA.Common.Measurement.GammaAnglePropulsor']
    propellerPitch: Optional['UMAA.Common.Measurement.PropellerPitchAnglePropulsor']
    propulsion: 'UMAA.Common.Measurement.FrequencyRPM'
    rho: Optional['UMAA.Common.Measurement.RhoAnglePropulsor']


