"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.UVPlatformSpecs
  IDL file: UnderwaterCapabilityLimitsType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class UnderwaterCapabilityLimitsType(idl.IdlStruct, typename="UMAA.EO.UVPlatformSpecs.UnderwaterCapabilityLimitsType"):
    cruisingSpeed: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    maxAcceleration: Optional['UMAA.Common.PrimitiveConstrained.AccelerationLocalWaterMass']
    maxAttitudeAcceleration: Optional['UMAA.Common.Measurement.OrientationAcceleration3D']
    maxAttitudeDeceleration: Optional['UMAA.Common.Measurement.OrientationAcceleration3D']
    maxDeceleration: Optional['UMAA.Common.PrimitiveConstrained.AccelerationLocalWaterMass']
    maxDepthAcceleration: Optional['UMAA.Common.PrimitiveConstrained.SpeedBSLAcceleration']
    maxDepthChangeRate: Optional['UMAA.Common.Measurement.SpeedBSL']
    maxForwardSpeed: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    maxPitchRate: Optional['UMAA.Common.Measurement.PitchRate']
    maxReverseSpeed: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    maxTowingSpeed: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    maxTowingTurnAcceleration: Optional['UMAA.Common.Measurement.AngleAcceleration']
    maxTowingTurnRate: Optional['UMAA.Common.Measurement.TurnRate']
    maxTurnAcceleration: Optional['UMAA.Common.Measurement.AngleAcceleration']
    maxTurnRate: Optional['UMAA.Common.Measurement.TurnRate']
    maxVehicleDepth: Optional['UMAA.Common.Measurement.DistanceBSL']
    minSpeedInMedium: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    minTowingSpeed: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']


