"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.UVPlatformSpecs
  IDL file: UVPlatformSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.ReferenceFrameOriginEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


UVPlatformSpecsReportTypeTopic = "UMAA::EO::UVPlatformSpecs::UVPlatformSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class UVPlatformSpecsReportType(idl.IdlStruct, typename="UMAA.EO.UVPlatformSpecs.UVPlatformSpecsReportType"):
    aftDistance: 'UMAA.Common.Measurement.Distance'
    beamAtWaterline: 'UMAA.Common.Measurement.Distance'
    bottomDistance: 'UMAA.Common.Measurement.Distance'
    centerOfBuoyancy: 'UMAA.Common.Measurement.Position3DBodyXYZ'
    centerOfGravity: 'UMAA.Common.Measurement.Position3DBodyXYZ'
    diameter: Optional['UMAA.Common.Measurement.Distance']
    displacement: 'UMAA.Common.Measurement.MassMetricTon'
    draft: 'UMAA.Common.Measurement.Distance'
    forwardDistance: 'UMAA.Common.Measurement.Distance'
    lengthAtWaterline: 'UMAA.Common.Measurement.Distance'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    portDistance: 'UMAA.Common.Measurement.Distance'
    referenceFrameOrigin: 'UMAA.Common.MaritimeEnumeration.ReferenceFrameOriginEnumModule.ReferenceFrameOriginEnumType'
    starboardDistance: 'UMAA.Common.Measurement.Distance'
    topDistance: 'UMAA.Common.Measurement.Distance'
    weightInWater: Optional['UMAA.Common.Measurement.MassMetricTon']
    weightLight: 'UMAA.Common.Measurement.MassMetricTon'
    weightLoaded: 'UMAA.Common.Measurement.MassMetricTon'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


