"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.UVPlatformSpecs
  IDL file: UVPlatformCapabilitiesReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


UVPlatformCapabilitiesReportTypeTopic = "UMAA::EO::UVPlatformSpecs::UVPlatformCapabilitiesReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class UVPlatformCapabilitiesReportType(idl.IdlStruct, typename="UMAA.EO.UVPlatformSpecs.UVPlatformCapabilitiesReportType"):
    minWaterDepth: 'UMAA.Common.Measurement.DistanceBSL'
    surfaceCapabilities: 'UMAA.EO.UVPlatformSpecs.SurfaceCapabilityLimitsType'
    towingCapacity: Optional['UMAA.Common.Measurement.MassMetricTon']
    underwaterCapabilities: Optional['UMAA.EO.UVPlatformSpecs.UnderwaterCapabilityLimitsType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


