"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.TranslationalShipMotionStatus
  IDL file: TranslationalShipMotionReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.MeasurementCoordinate
    import UMAA.Common.PrimitiveConstrained


TranslationalShipMotionReportTypeTopic = "UMAA::SA::TranslationalShipMotionStatus::TranslationalShipMotionReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TranslationalShipMotionReportType(idl.IdlStruct, typename="UMAA.SA.TranslationalShipMotionStatus.TranslationalShipMotionReportType"):
    heave: Optional['UMAA.Common.MeasurementCoordinate.Down']
    surge: Optional['UMAA.Common.MeasurementCoordinate.Forward']
    sway: Optional['UMAA.Common.PrimitiveConstrained.Left']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


