services:
  umaapy-dev:
    image: dkreed747/umaapy-dev:latest
    container_name: umaapy-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: develop
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    networks:
      - net

networks:
  net:
    name: umaapy-dev-network
    external: false
