"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.EmitterSpecs
  IDL file: EmitterSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


EmitterSpecsReportTypeTopic = "UMAA::SO::EmitterSpecs::EmitterSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EmitterSpecsReportType(idl.IdlStruct, typename="UMAA.SO.EmitterSpecs.EmitterSpecsReportType"):
    frequencyBand: types.sequence['UMAA.Common.Measurement.ElectroMagneticFrequencyHertz', 16]
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    emitterID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("emitterID")


