"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactVisualClassificationStatus
  IDL file: ContactVisualClassificationReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.VisualClassificationEnumModule
    import UMAA.Common.Measurement


ContactVisualClassificationReportTypeTopic = "UMAA::SA::ContactVisualClassificationStatus::ContactVisualClassificationReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactVisualClassificationReportType(idl.IdlStruct, typename="UMAA.SA.ContactVisualClassificationStatus.ContactVisualClassificationReportType"):
    confidence: 'UMAA.Common.Measurement.Percent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")
    visualClassification: 'UMAA.Common.MaritimeEnumeration.VisualClassificationEnumModule.VisualClassificationEnumType'
    annotate.key("visualClassification")


