"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.PassiveContactReport
  IDL file: PassiveContactType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.PassiveContactFeatureEnumModule
    import UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.MeasurementConstrained
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PassiveContactType(idl.IdlStruct, typename="UMAA.SA.PassiveContactReport.PassiveContactType"):
    bearing: 'UMAA.Common.PrimitiveConstrained.BearingAngle'
    bearingRate: 'UMAA.Common.Measurement.AngleRate'
    bearingRateUncertainty: 'UMAA.Common.PrimitiveConstrained.ContactUncertainty'
    bearingUncertainty: 'UMAA.Common.PrimitiveConstrained.ContactUncertainty'
    contactLevel: 'UMAA.Common.PrimitiveConstrained.PeakSoundPressureLevel'
    contactType: Optional['UMAA.Common.MaritimeEnumeration.PassiveContactFeatureEnumModule.PassiveContactFeatureEnumType']
    course: Optional['UMAA.Common.Measurement.CourseTrueNorth']
    courseUncertainty: Optional['UMAA.Common.PrimitiveConstrained.ContactUncertainty']
    declination: Optional['UMAA.Common.MeasurementConstrained.AngleHalf']
    declinationUncertainty: Optional['UMAA.Common.PrimitiveConstrained.ContactUncertainty']
    narrowbandContactFrequency: Optional['UMAA.Common.Measurement.FrequencyHertz']
    range: Optional['UMAA.Common.Measurement.Distance']
    rangeUncertainty: Optional['UMAA.Common.PrimitiveConstrained.ContactUncertainty']
    threatType: Optional['UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule.TrackIdentityEnumType']


