"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.OperationalModeStatus
  IDL file: OperationalModeReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.OperationalModeEnumModule
    import UMAA.Common.Measurement


OperationalModeReportTypeTopic = "UMAA::MM::OperationalModeStatus::OperationalModeReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class OperationalModeReportType(idl.IdlStruct, typename="UMAA.MM.OperationalModeStatus.OperationalModeReportType"):
    operationalMode: 'UMAA.Common.MaritimeEnumeration.OperationalModeEnumModule.OperationalModeEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


