"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelSpecs

"""

from ._CommsChannelSpecsReportType import CommsChannelSpecsReportType, CommsChannelSpecsReportTypeTopic
from ._FrequencyRangeType import FrequencyRangeType
__all__ = [
	"CommsChannelSpecsReportType",
	"CommsChannelSpecsReportTypeTopic",
	"FrequencyRangeType",
]
