"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelSpecs
  IDL file: CommsChannelSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


CommsChannelSpecsReportTypeTopic = "UMAA::CO::CommsChannelSpecs::CommsChannelSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelSpecsReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelSpecs.CommsChannelSpecsReportType"):
    bufferSize: 'UMAA.Common.Measurement.SizeBytes'
    commsDeviceIdentifier: Optional['UMAA.Common.PrimitiveConstrained.StringShortDescription']
    maxTransmitPower: 'UMAA.Common.Measurement.ElectricalPower'
    minimumSNR: 'UMAA.Common.PrimitiveConstrained.SignalToNoiseRatio'
    spectrumRange: 'UMAA.CO.CommsChannelSpecs.FrequencyRangeType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


