"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ConditionalStateReport
  IDL file: ConditionalStateReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


ConditionalStateReportTypeTopic = "UMAA::MM::ConditionalStateReport::ConditionalStateReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ConditionalStateReportType(idl.IdlStruct, typename="UMAA.MM.ConditionalStateReport.ConditionalStateReportType"):
    state: bool
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    conditionalID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("conditionalID")


