"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateReasonEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ObjectiveExecutorStateReasonEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateReasonEnumModule.ObjectiveExecutorStateReasonEnumType", default="BUS_MSG_DISPOSE"):
    BUS_MSG_DISPOSE = auto()
    BUS_MSG_UPDATE = auto()
    CANNOT_PERFORM_UNDER_CONSTRAINTS = auto()
    COMMAND_VALIDATION_FAILED = auto()
    COMMANDED = auto()
    INTERNAL_FAILURE = auto()
    LOWER_SERVICE_FAILED = auto()
    LOWER_SERVICE_INTERRUPTED = auto()
    LOWER_SERVICE_REJECTED = auto()
    LOWER_SERVICE_TIMEOUT = auto()
    OBJECTIVE_REPLACED = auto()
    SUCCEEDED = auto()

