"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Speed
  IDL file: VariableSpeedVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class VariableSpeedVariantTypeEnum(idl.IdlEnum, typename="UMAA.Common.Speed.VariableSpeedVariantTypeEnum", default="RECOMMENDEDSPEEDVARIANT_D"):
    RECOMMENDEDSPEEDVARIANT_D = auto()
    REQUIREDSPEEDVARIANT_D = auto()
    TIMEWITHSPEEDVARIANT_D = auto()


@annotate.final
@annotate.nested
class VariableSpeedVariantTypeUnion(idl.IdlUnion, discriminator=VariableSpeedVariantTypeEnum, discriminator_is_key=False, typename="UMAA.Common.Speed.VariableSpeedVariantTypeUnion"):
    RecommendedSpeedVariantVariant: types.case[[VariableSpeedVariantTypeEnum.RECOMMENDEDSPEEDVARIANT_D], 'UMAA.Common.Speed.RecommendedSpeedVariantType']
    RequiredSpeedVariantVariant: types.case[[VariableSpeedVariantTypeEnum.REQUIREDSPEEDVARIANT_D], 'UMAA.Common.Speed.RequiredSpeedVariantType']
    TimeWithSpeedVariantVariant: types.case[[VariableSpeedVariantTypeEnum.TIMEWITHSPEEDVARIANT_D], 'UMAA.Common.Speed.TimeWithSpeedVariantType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class VariableSpeedVariantType(idl.IdlStruct, typename="UMAA.Common.Speed.VariableSpeedVariantType"):
    VariableSpeedVariantTypeSubtypes: 'UMAA.Common.Speed.VariableSpeedVariantTypeUnion'


