"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Speed
  IDL file: VehicleSpeedModeRequirementVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.VehicleSpeedModeEnumModule



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class VehicleSpeedModeRequirementVariantType(idl.IdlStruct, typename="UMAA.Common.Speed.VehicleSpeedModeRequirementVariantType"):
    mode: 'UMAA.Common.MaritimeEnumeration.VehicleSpeedModeEnumModule.VehicleSpeedModeEnumType'


