"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.FLSPreCalcControl
  IDL file: FLSPreCalcCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.FLSConfigModeEnumModule
    import UMAA.Common.Measurement
    import UMAA.SEM.BaseType


FLSPreCalcCommandTypeTopic = "UMAA::SEM::FLSPreCalcControl::FLSPreCalcCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class FLSPreCalcCommandType(idl.IdlStruct, typename="UMAA.SEM.FLSPreCalcControl.FLSPreCalcCommandType"):
    additionalConfig: Optional['UMAA.SEM.BaseType.FLSAdditionalConfigType']
    configMode: 'UMAA.Common.MaritimeEnumeration.FLSConfigModeEnumModule.FLSConfigModeEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


