import pytest
import importlib
import inspect


class TestTypes:
    def test_autogenerated_types_available(self):
        importlib.import_module("umaapy.types")

    def test_import_global_pose_report(self):
        from umaapy.types import UMAA_SA_GlobalPoseStatus_GlobalPoseReportType
