"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.CompartmentConfig

"""

from ._CompartmentConfigReportType import CompartmentConfigReportType, CompartmentConfigReportTypeTopic
__all__ = [
	"CompartmentConfigReportType",
	"CompartmentConfigReportTypeTopic",
]
