"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BatterySpecs

"""

from ._BatterySpecsReportType import BatterySpecsReportType, BatterySpecsReportTypeTopic
__all__ = [
	"BatterySpecsReportType",
	"BatterySpecsReportTypeTopic",
]
