"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BatterySpecs
  IDL file: BatterySpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


BatterySpecsReportTypeTopic = "UMAA::EO::BatterySpecs::BatterySpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BatterySpecsReportType(idl.IdlStruct, typename="UMAA.EO.BatterySpecs.BatterySpecsReportType"):
    cellMinimumVoltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    maxCapacity: 'UMAA.Common.Measurement.Charge'
    maxChargingCurrent: 'UMAA.Common.Measurement.PowerBusCurrent'
    maxChargingTemp: 'UMAA.Common.Measurement.Temperature'
    maxOutputCurrent: 'UMAA.Common.Measurement.PowerBusCurrent'
    maxPulsedChargeCurrent: Optional['UMAA.Common.Measurement.BatteryCurrent']
    maxPulsedChargeCurrentDuration: Optional['UMAA.Common.Measurement.BatteryCurrentDuration']
    maxStorageTemp: 'UMAA.Common.Measurement.Temperature'
    maxTemperature: 'UMAA.Common.Measurement.Temperature'
    maxVoltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    minChargeCycles: Optional['UMAA.Common.Measurement.BatteryCycles']
    minChargingTemp: 'UMAA.Common.Measurement.Temperature'
    minStorageTemp: 'UMAA.Common.Measurement.Temperature'
    minTemperature: 'UMAA.Common.Measurement.Temperature'
    minVoltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    nominalCapacity: 'UMAA.Common.Measurement.AmpHours'
    nominalEnergy: 'UMAA.Common.Measurement.WattHours'
    nominalVoltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    peakDischargeCurrent: 'UMAA.Common.Measurement.PowerBusCurrent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


