"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelSystemTimeReport

"""

from ._CommsChannelSystemTimeReportType import CommsChannelSystemTimeReportType, CommsChannelSystemTimeReportTypeTopic
__all__ = [
	"CommsChannelSystemTimeReportType",
	"CommsChannelSystemTimeReportTypeTopic",
]
