"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BatteryStatus
  IDL file: BatteryReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.PowerPlantStateEnumModule
    import UMAA.Common.Measurement


BatteryReportTypeTopic = "UMAA::EO::BatteryStatus::BatteryReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BatteryReportType(idl.IdlStruct, typename="UMAA.EO.BatteryStatus.BatteryReportType"):
    chargeRemaining: Optional['UMAA.Common.Measurement.EnergyPercent']
    current: Optional['UMAA.Common.Measurement.PowerBusCurrent']
    energyUsageRate: Optional['UMAA.Common.Measurement.ElectricalPower']
    hours: Optional['UMAA.Common.Measurement.DurationHours']
    state: 'UMAA.Common.MaritimeEnumeration.PowerPlantStateEnumModule.PowerPlantStateEnumType'
    temp: Optional['UMAA.Common.Measurement.Temperature']
    voltage: Optional['UMAA.Common.Measurement.PowerBusVoltage']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    cellsListMetadata: 'UMAA.Common.LargeListMetadata'

BatteryReportTypeCellsListElementTopic = "UMAA::EO::BatteryStatus::BatteryReportTypeCellsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BatteryReportTypeCellsListElement(idl.IdlStruct, typename="UMAA.EO.BatteryStatus.BatteryReportTypeCellsListElement"):
    element: 'UMAA.EO.BatteryStatus.BatteryCellDataType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']


