"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.ContactManeuverInfluenceStatus

"""

from ._ContactManeuverInfluenceReportType import ContactManeuverInfluenceReportType, ContactManeuverInfluenceReportTypeTopic
__all__ = [
	"ContactManeuverInfluenceReportType",
	"ContactManeuverInfluenceReportTypeTopic",
]
