"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.ContactManeuverInfluenceStatus
  IDL file: ContactManeuverInfluenceReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.ContactManeuverInfluenceEnumModule
    import UMAA.Common.Measurement


ContactManeuverInfluenceReportTypeTopic = "UMAA::MO::ContactManeuverInfluenceStatus::ContactManeuverInfluenceReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactManeuverInfluenceReportType(idl.IdlStruct, typename="UMAA.MO.ContactManeuverInfluenceStatus.ContactManeuverInfluenceReportType"):
    influence: 'UMAA.Common.MaritimeEnumeration.ContactManeuverInfluenceEnumModule.ContactManeuverInfluenceEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")


