"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.EngineControl
  IDL file: EngineCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Enumeration.OnOffStatusEnumModule
    import UMAA.Common.MaritimeEnumeration.IgnitionControlEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.Propulsion


EngineCommandTypeTopic = "UMAA::EO::EngineControl::EngineCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EngineCommandType(idl.IdlStruct, typename="UMAA.EO.EngineControl.EngineCommandType"):
    plugState: Optional['UMAA.Common.Enumeration.OnOffStatusEnumModule.OnOffStatusEnumType']
    propulsion: Optional['UMAA.Common.Propulsion.PropulsionType']
    state: 'UMAA.Common.MaritimeEnumeration.IgnitionControlEnumModule.IgnitionControlEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


