"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactIdentityReport

"""

from ._ContactIdentityReportType import ContactIdentityReportType, ContactIdentityReportTypeTopic
__all__ = [
	"ContactIdentityReportType",
	"ContactIdentityReportTypeTopic",
]
