"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactIdentityReport
  IDL file: ContactIdentityReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule
    import UMAA.Common.Measurement


ContactIdentityReportTypeTopic = "UMAA::SA::ContactIdentityReport::ContactIdentityReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactIdentityReportType(idl.IdlStruct, typename="UMAA.SA.ContactIdentityReport.ContactIdentityReportType"):
    confidence: 'UMAA.Common.Measurement.Percent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")
    identity: 'UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule.TrackIdentityEnumType'
    annotate.key("identity")


