"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ContinuousTestEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ContinuousTestEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ContinuousTestEnumModule.ContinuousTestEnumType", default="DISABLED_NO_TEST"):
    DISABLED_NO_TEST = auto()
    FULL_TEST = auto()
    NON_INTRUSIVE_TESTS_ONLY = auto()

