"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.LogLevelEnumModule

"""

from ._MaritimeEnumerationSets import LogLevelEnumType
__all__ = [
	"LogLevelEnumType",
]
