"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ControlTransfer
  IDL file: ClientControlReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Enumeration.ResourceAllocationStatusEnumModule
    import UMAA.Common.Measurement


ClientControlReportTypeTopic = "UMAA::MM::ControlTransfer::ClientControlReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ClientControlReportType(idl.IdlStruct, typename="UMAA.MM.ControlTransfer.ClientControlReportType"):
    authorityLevel: 'UMAA.Common.Measurement.Count'
    clientID: 'UMAA.Common.IdentifierType'
    status: 'UMAA.Common.Enumeration.ResourceAllocationStatusEnumModule.ResourceAllocationStatusEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


