"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ControlTransfer
  IDL file: ControlSystemTransferReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.HandoverResultEnumModule
    import UMAA.Common.Measurement


ControlSystemTransferReportTypeTopic = "UMAA::MM::ControlTransfer::ControlSystemTransferReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ControlSystemTransferReportType(idl.IdlStruct, typename="UMAA.MM.ControlTransfer.ControlSystemTransferReportType"):
    authorityLevel: 'UMAA.Common.Measurement.Count'
    result: 'UMAA.Common.MaritimeEnumeration.HandoverResultEnumModule.HandoverResultEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


