"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.DomainEnumModule

"""

from ._MaritimeEnumerationSets import DomainEnumType
__all__ = [
	"DomainEnumType",
]
