"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.LogReport
  IDL file: LogReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.LogLevelEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


LogReportTypeTopic = "UMAA::SO::LogReport::LogReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LogReportType(idl.IdlStruct, typename="UMAA.SO.LogReport.LogReportType"):
    entry: 'UMAA.Common.PrimitiveConstrained.StringLongDescription'
    level: 'UMAA.Common.MaritimeEnumeration.LogLevelEnumModule.LogLevelEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


