"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Orientation
  IDL file: BearingSectorTrueNorthVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class BearingSectorTrueNorthVariantType(idl.IdlStruct, typename="UMAA.Common.Orientation.BearingSectorTrueNorthVariantType"):
    endBearing: 'UMAA.Common.Measurement.HeadingTrueNorthAngle'
    startBearing: 'UMAA.Common.Measurement.HeadingTrueNorthAngle'


