"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Orientation
  IDL file: BearingSectorVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class BearingSectorVariantTypeEnum(idl.IdlEnum, typename="UMAA.Common.Orientation.BearingSectorVariantTypeEnum", default="BEARINGSECTORGUIDECOURSEVARIANT_D"):
    BEARINGSECTORGUIDECOURSEVARIANT_D = auto()
    BEARINGSECTORMAGNETICNORTHVARIANT_D = auto()
    BEARINGSECTORTRUENORTHVARIANT_D = auto()


@annotate.final
@annotate.nested
class BearingSectorVariantTypeUnion(idl.IdlUnion, discriminator=BearingSectorVariantTypeEnum, discriminator_is_key=False, typename="UMAA.Common.Orientation.BearingSectorVariantTypeUnion"):
    BearingSectorGuideCourseVariantVariant: types.case[[BearingSectorVariantTypeEnum.BEARINGSECTORGUIDECOURSEVARIANT_D], 'UMAA.Common.Orientation.BearingSectorGuideCourseVariantType']
    BearingSectorMagneticNorthVariantVariant: types.case[[BearingSectorVariantTypeEnum.BEARINGSECTORMAGNETICNORTHVARIANT_D], 'UMAA.Common.Orientation.BearingSectorMagneticNorthVariantType']
    BearingSectorTrueNorthVariantVariant: types.case[[BearingSectorVariantTypeEnum.BEARINGSECTORTRUENORTHVARIANT_D], 'UMAA.Common.Orientation.BearingSectorTrueNorthVariantType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class BearingSectorVariantType(idl.IdlStruct, typename="UMAA.Common.Orientation.BearingSectorVariantType"):
    BearingSectorVariantTypeSubtypes: 'UMAA.Common.Orientation.BearingSectorVariantTypeUnion'


