"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Orientation
  IDL file: DirectionRequirementVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class DirectionRequirementVariantTypeEnum(idl.IdlEnum, typename="UMAA.Common.Orientation.DirectionRequirementVariantTypeEnum", default="DIRECTIONCURRENTREQUIREMENTVARIANT_D"):
    DIRECTIONCURRENTREQUIREMENTVARIANT_D = auto()
    DIRECTIONMAGNETICNORTHREQUIREMENTVARIANT_D = auto()
    DIRECTIONTRUENORTHREQUIREMENTVARIANT_D = auto()
    DIRECTIONTURNRATEREQUIREMENTVARIANT_D = auto()
    DIRECTIONWINDREQUIREMENTVARIANT_D = auto()


@annotate.final
@annotate.nested
class DirectionRequirementVariantTypeUnion(idl.IdlUnion, discriminator=DirectionRequirementVariantTypeEnum, discriminator_is_key=False, typename="UMAA.Common.Orientation.DirectionRequirementVariantTypeUnion"):
    DirectionCurrentRequirementVariantVariant: types.case[[DirectionRequirementVariantTypeEnum.DIRECTIONCURRENTREQUIREMENTVARIANT_D], 'UMAA.Common.Orientation.DirectionCurrentRequirementVariantType']
    DirectionMagneticNorthRequirementVariantVariant: types.case[[DirectionRequirementVariantTypeEnum.DIRECTIONMAGNETICNORTHREQUIREMENTVARIANT_D], 'UMAA.Common.Orientation.DirectionMagneticNorthRequirementVariantType']
    DirectionTrueNorthRequirementVariantVariant: types.case[[DirectionRequirementVariantTypeEnum.DIRECTIONTRUENORTHREQUIREMENTVARIANT_D], 'UMAA.Common.Orientation.DirectionTrueNorthRequirementVariantType']
    DirectionTurnRateRequirementVariantVariant: types.case[[DirectionRequirementVariantTypeEnum.DIRECTIONTURNRATEREQUIREMENTVARIANT_D], 'UMAA.Common.Orientation.DirectionTurnRateRequirementVariantType']
    DirectionWindRequirementVariantVariant: types.case[[DirectionRequirementVariantTypeEnum.DIRECTIONWINDREQUIREMENTVARIANT_D], 'UMAA.Common.Orientation.DirectionWindRequirementVariantType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class DirectionRequirementVariantType(idl.IdlStruct, typename="UMAA.Common.Orientation.DirectionRequirementVariantType"):
    DirectionRequirementVariantTypeSubtypes: 'UMAA.Common.Orientation.DirectionRequirementVariantTypeUnion'


