"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Orientation
  IDL file: PitchYNEDRequirement.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PitchYNEDRequirement(idl.IdlStruct, typename="UMAA.Common.Orientation.PitchYNEDRequirement"):
    pitch: 'UMAA.Common.Orientation.PitchYNEDType'
    pitchTolerance: Optional['UMAA.Common.Orientation.PitchYNEDTolerance']


