"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ImageFormatEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ImageFormatEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ImageFormatEnumModule.ImageFormatEnumType", default="ARW"):
    ARW = auto()
    BMP = auto()
    CR2_RAW = auto()
    DNG = auto()
    GEOJPEG = auto()
    GEOTIFF = auto()
    GIF = auto()
    GPR = auto()
    JPEG = auto()
    NEF = auto()
    PGM = auto()
    PNG = auto()
    PNM = auto()
    PPM = auto()
    TIFF = auto()

