"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Propulsion
  IDL file: PropulsionType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class PropulsionTypeEnum(idl.IdlEnum, typename="UMAA.Common.Propulsion.PropulsionTypeEnum", default="PROPULSIVEEFFORT_D"):
    PROPULSIVEEFFORT_D = auto()
    PROPULSIVERPM_D = auto()


@annotate.final
@annotate.nested
class PropulsionTypeUnion(idl.IdlUnion, discriminator=PropulsionTypeEnum, discriminator_is_key=False, typename="UMAA.Common.Propulsion.PropulsionTypeUnion"):
    PropulsiveEffortVariant: types.case[[PropulsionTypeEnum.PROPULSIVEEFFORT_D], 'UMAA.Common.Propulsion.PropulsiveEffortType']
    PropulsiveRPMVariant: types.case[[PropulsionTypeEnum.PROPULSIVERPM_D], 'UMAA.Common.Propulsion.PropulsiveRPMType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PropulsionType(idl.IdlStruct, typename="UMAA.Common.Propulsion.PropulsionType"):
    PropulsionTypeSubtypes: 'UMAA.Common.Propulsion.PropulsionTypeUnion'


