"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WaterCurrentStatus

"""

from ._WaterCurrentReportType import WaterCurrentReportType, WaterCurrentReportTypeTopic
__all__ = [
	"WaterCurrentReportType",
	"WaterCurrentReportTypeTopic",
]
