"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WaterCurrentStatus
  IDL file: WaterCurrentReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


WaterCurrentReportTypeTopic = "UMAA::SA::WaterCurrentStatus::WaterCurrentReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class WaterCurrentReportType(idl.IdlStruct, typename="UMAA.SA.WaterCurrentStatus.WaterCurrentReportType"):
    currentDirection: 'UMAA.Common.Measurement.HeadingTrueNorthAngle'
    currentSpeed: 'UMAA.Common.Measurement.Speed'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


