"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: AltitudeRateASFToleranceType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class AltitudeRateASFToleranceType(idl.IdlStruct, typename="UMAA.Common.Measurement.AltitudeRateASFToleranceType"):
    failureDelay: Optional['UMAA.Common.Measurement.DurationSeconds']
    lowerLimit: 'UMAA.Common.Measurement.SpeedASF'
    upperlimit: 'UMAA.Common.Measurement.SpeedASF'


