"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovarianceVelocityNEDType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovarianceVelocityNEDType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovarianceVelocityNEDType"):
    vdVd: Optional['UMAA.Common.PrimitiveConstrained.CovarVelNED']
    veVd: Optional['UMAA.Common.PrimitiveConstrained.CovarVelNED']
    veVe: 'UMAA.Common.PrimitiveConstrained.CovarVelNED'
    vnVd: Optional['UMAA.Common.PrimitiveConstrained.CovarVelNED']
    vnVe: Optional['UMAA.Common.PrimitiveConstrained.CovarVelNED']
    vnVn: 'UMAA.Common.PrimitiveConstrained.CovarVelNED'


