"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovariancePositionNEDType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovariancePositionNEDType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovariancePositionNEDType"):
    pdPd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosNED']
    pePd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosNED']
    pePe: 'UMAA.Common.PrimitiveConstrained.CovarPosNED'
    pnPd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosNED']
    pnPe: Optional['UMAA.Common.PrimitiveConstrained.CovarPosNED']
    pnPn: 'UMAA.Common.PrimitiveConstrained.CovarPosNED'


