"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovarianceOrientationAccelerationPlatformXYZType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovarianceOrientationAccelerationPlatformXYZType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovarianceOrientationAccelerationPlatformXYZType"):
    rxRx: 'UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ'
    rxRy: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ']
    rxRz: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ']
    ryRy: 'UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ'
    ryRz: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ']
    rzRz: 'UMAA.Common.PrimitiveConstrained.CovarOrientationAccelPlatformXYZ'


