"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovarianceAccelerationPlatformXYZType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovarianceAccelerationPlatformXYZType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovarianceAccelerationPlatformXYZType"):
    axAx: 'UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ'
    axAy: Optional['UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ']
    axAz: Optional['UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ']
    ayAy: 'UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ'
    ayAz: Optional['UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ']
    azAz: 'UMAA.Common.PrimitiveConstrained.CovarAccelPlatformXYZ'


