"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovariancePositionVelocityNEDType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovariancePositionVelocityNEDType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovariancePositionVelocityNEDType"):
    pdVd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    pdVe: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    pdVn: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    peVd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    peVe: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    peVn: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    pnVd: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    pnVe: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']
    pnVn: Optional['UMAA.Common.PrimitiveConstrained.CovarPosVelNED']


