"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovarianceOrientationNEDType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovarianceOrientationNEDType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovarianceOrientationNEDType"):
    rpRp: 'UMAA.Common.PrimitiveConstrained.CovarOrientationNED'
    rpRy: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationNED']
    rrRp: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationNED']
    rrRr: 'UMAA.Common.PrimitiveConstrained.CovarOrientationNED'
    rrRy: Optional['UMAA.Common.PrimitiveConstrained.CovarOrientationNED']
    ryRy: 'UMAA.Common.PrimitiveConstrained.CovarOrientationNED'


