"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: CovariancePositionECEFType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CovariancePositionECEFType(idl.IdlStruct, typename="UMAA.Common.Measurement.CovariancePositionECEFType"):
    pxPx: 'UMAA.Common.PrimitiveConstrained.CovarPosECEF'
    pxPy: Optional['UMAA.Common.PrimitiveConstrained.CovarPosECEF']
    pxPz: Optional['UMAA.Common.PrimitiveConstrained.CovarPosECEF']
    pyPy: 'UMAA.Common.PrimitiveConstrained.CovarPosECEF'
    pyPz: Optional['UMAA.Common.PrimitiveConstrained.CovarPosECEF']
    pzPz: Optional['UMAA.Common.PrimitiveConstrained.CovarPosECEF']


