"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: GeoPosition2D.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MeasurementCoordinate



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GeoPosition2D(idl.IdlStruct, typename="UMAA.Common.Measurement.GeoPosition2D"):
    geodeticLatitude: 'UMAA.Common.MeasurementCoordinate.GeodeticLatitude'
    geodeticLongitude: 'UMAA.Common.MeasurementCoordinate.GeodeticLongitude'


