"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: GeoPosition3DWGS84.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GeoPosition3DWGS84(idl.IdlStruct, typename="UMAA.Common.Measurement.GeoPosition3DWGS84"):
    geodeticAltitude: 'UMAA.Common.PrimitiveConstrained.GeodeticAltitude'
    geodeticPosition: 'UMAA.Common.Measurement.GeoPosition2D'


