"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: Measurements.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

AmpHours_MIN = 0.000000
AmpHours_MAX = 500.000000
AmpHours = types.typedef['UMAA.Common.Measurement.AmpHours', types.float64]
AngleAcceleration_MIN = -10000.000000
AngleAcceleration_MAX = 10000.000000
AngleAcceleration = types.typedef['UMAA.Common.Measurement.AngleAcceleration', types.float64]
AzimuthTrueNorthAngle_MIN = -6.283185
AzimuthTrueNorthAngle_MAX = 6.283185
AzimuthTrueNorthAngle = types.typedef['UMAA.Common.Measurement.AzimuthTrueNorthAngle', types.float64]
BatteryCurrent_MIN = 0.000000
BatteryCurrent_MAX = 1000.000000
BatteryCurrent = types.typedef['UMAA.Common.Measurement.BatteryCurrent', types.float64]
BatteryCurrentDuration_MIN = 0.000000
BatteryCurrentDuration_MAX = 20.000000
BatteryCurrentDuration = types.typedef['UMAA.Common.Measurement.BatteryCurrentDuration', types.float64]
BatteryCycles_MIN = 0.000000
BatteryCycles_MAX = 10000.000000
BatteryCycles = types.typedef['UMAA.Common.Measurement.BatteryCycles', types.float64]
BinaryValue = types.typedef['UMAA.Common.Measurement.BinaryValue', types.array[types.byte, 256]]
ByteValue = types.typedef['UMAA.Common.Measurement.ByteValue', types.byte]
Charge_MIN = 0.000000
Charge_MAX = 3600000.000000
Charge = types.typedef['UMAA.Common.Measurement.Charge', types.float64]
CharValue = types.typedef['UMAA.Common.Measurement.CharValue', types.char]
Conductivity = types.typedef['UMAA.Common.Measurement.Conductivity', types.float64]
DataTransferRate_MIN = 0.000000
DataTransferRate = types.typedef['UMAA.Common.Measurement.DataTransferRate', types.float64]
DistanceASF_MIN = 0.000000
DistanceASF_MAX = 401056000.000000
DistanceASF = types.typedef['UMAA.Common.Measurement.DistanceASF', types.float64]
DistanceBSL_MIN = 0.000000
DistanceBSL_MAX = 10000.000000
DistanceBSL = types.typedef['UMAA.Common.Measurement.DistanceBSL', types.float64]
DistanceAGL_MIN = 0.000000
DistanceAGL = types.typedef['UMAA.Common.Measurement.DistanceAGL', types.float64]
DoubleValue = types.typedef['UMAA.Common.Measurement.DoubleValue', types.float64]
DurationMilliseconds_MIN = 0.000000
DurationMilliseconds = types.typedef['UMAA.Common.Measurement.DurationMilliseconds', types.float64]
Effort_MIN = -100.000000
Effort_MAX = 100.000000
Effort = types.typedef['UMAA.Common.Measurement.Effort', types.float64]
ElectroMagneticFrequencyHertz_MIN = 0.000000
ElectroMagneticFrequencyHertz_MAX = 10000000000000000905969664.000000
ElectroMagneticFrequencyHertz = types.typedef['UMAA.Common.Measurement.ElectroMagneticFrequencyHertz', types.float64]
EnergyPercent_MIN = 0.000000
EnergyPercent_MAX = 1000.000000
EnergyPercent = types.typedef['UMAA.Common.Measurement.EnergyPercent', types.float64]
FrequencyRPM_MIN = -100000
FrequencyRPM_MAX = 100000
FrequencyRPM = types.typedef['UMAA.Common.Measurement.FrequencyRPM', types.int32]
GammaAnglePropulsor_MIN = -6.283185
GammaAnglePropulsor_MAX = 6.283185
GammaAnglePropulsor = types.typedef['UMAA.Common.Measurement.GammaAnglePropulsor', types.float64]
HeadingCurrentDirection_MIN = -6.283185
HeadingCurrentDirection_MAX = 6.283185
HeadingCurrentDirection = types.typedef['UMAA.Common.Measurement.HeadingCurrentDirection', types.float64]
HeadingMagneticNorth_MIN = -6.283185
HeadingMagneticNorth_MAX = 6.283185
HeadingMagneticNorth = types.typedef['UMAA.Common.Measurement.HeadingMagneticNorth', types.float64]
HeadingTarget_MIN = -6.283185
HeadingTarget_MAX = 6.283185
HeadingTarget = types.typedef['UMAA.Common.Measurement.HeadingTarget', types.float64]
HeadingWindDirection_MIN = -6.283185
HeadingWindDirection_MAX = 6.283185
HeadingWindDirection = types.typedef['UMAA.Common.Measurement.HeadingWindDirection', types.float64]
IntegerValue = types.typedef['UMAA.Common.Measurement.IntegerValue', types.int32]
LargeCount = types.typedef['UMAA.Common.Measurement.LargeCount', types.uint64]
MassMetricTon_MIN = 0.000000
MassMetricTon_MAX = 100000.000000
MassMetricTon = types.typedef['UMAA.Common.Measurement.MassMetricTon', types.float64]
MassFlowRate = types.typedef['UMAA.Common.Measurement.MassFlowRate', types.float64]
MSLAltitude_MIN = 0.000000
MSLAltitude = types.typedef['UMAA.Common.Measurement.MSLAltitude', types.float64]
PressurePercent_MIN = 0.000000
PressurePercent_MAX = 200.000000
PressurePercent = types.typedef['UMAA.Common.Measurement.PressurePercent', types.float64]
Priority_MIN = 0
Priority_MAX = 255
Priority = types.typedef['UMAA.Common.Measurement.Priority', types.int32]
PropellerPitchAnglePropulsor_MIN = -6.283185
PropellerPitchAnglePropulsor_MAX = 6.283185
PropellerPitchAnglePropulsor = types.typedef['UMAA.Common.Measurement.PropellerPitchAnglePropulsor', types.float64]
RhoAnglePropulsor_MIN = -6.283185
RhoAnglePropulsor_MAX = 6.283185
RhoAnglePropulsor = types.typedef['UMAA.Common.Measurement.RhoAnglePropulsor', types.float64]
Salinity = types.typedef['UMAA.Common.Measurement.Salinity', types.float64]
SegmentID_MIN = 0
SegmentID_MAX = 100000
SegmentID = types.typedef['UMAA.Common.Measurement.SegmentID', types.int32]
SidesCount_MIN = 3
SidesCount_MAX = 255
SidesCount = types.typedef['UMAA.Common.Measurement.SidesCount', types.int32]
SizeLargeBytes = types.typedef['UMAA.Common.Measurement.SizeLargeBytes', types.uint64]
SpeedASF_MIN = -299792458.000000
SpeedASF_MAX = 299792458.000000
SpeedASF = types.typedef['UMAA.Common.Measurement.SpeedASF', types.float64]
SpeedBSL_MIN = -299792458.000000
SpeedBSL_MAX = 299792458.000000
SpeedBSL = types.typedef['UMAA.Common.Measurement.SpeedBSL', types.float64]
SpeedLocalWaterMass_MIN = 0.000000
SpeedLocalWaterMass_MAX = 299792458.000000
SpeedLocalWaterMass = types.typedef['UMAA.Common.Measurement.SpeedLocalWaterMass', types.float64]
TransmitAttenuation_MIN = 0
TransmitAttenuation_MAX = 18
TransmitAttenuation = types.typedef['UMAA.Common.Measurement.TransmitAttenuation', types.int32]
Turbidity_MIN = 0.000000
Turbidity = types.typedef['UMAA.Common.Measurement.Turbidity', types.float64]
VolumeCubicMeter_MIN = 0.000000
VolumeCubicMeter_MAX = 1000.000000
VolumeCubicMeter = types.typedef['UMAA.Common.Measurement.VolumeCubicMeter', types.float64]
VolumePercent_MIN = 0.000000
VolumePercent_MAX = 1000.000000
VolumePercent = types.typedef['UMAA.Common.Measurement.VolumePercent', types.float64]
VolumetricFlowRate_MIN = -100000000.000000
VolumetricFlowRate_MAX = 100000000.000000
VolumetricFlowRate = types.typedef['UMAA.Common.Measurement.VolumetricFlowRate', types.float64]
WattHours_MIN = 0.000000
WattHours_MAX = 900000.000000
WattHours = types.typedef['UMAA.Common.Measurement.WattHours', types.float64]
YawAngle_MIN = -6.283185
YawAngle_MAX = 6.283185
YawAngle = types.typedef['UMAA.Common.Measurement.YawAngle', types.float64]
AccelerationScalar_MIN = -1310.680000
AccelerationScalar_MAX = 1310.680000
AccelerationScalar = types.typedef['UMAA.Common.Measurement.AccelerationScalar', types.float64]
Angle_MIN = -3.141593
Angle_MAX = 3.141593
Angle = types.typedef['UMAA.Common.Measurement.Angle', types.float64]
AngleRate_MIN = -62.831000
AngleRate_MAX = 62.831000
AngleRate = types.typedef['UMAA.Common.Measurement.AngleRate', types.float64]
Count_MIN = -2147483648
Count_MAX = 2147483647
Count = types.typedef['UMAA.Common.Measurement.Count', types.int32]
CourseTrueNorth_MIN = -6.283185
CourseTrueNorth_MAX = 6.283185
CourseTrueNorth = types.typedef['UMAA.Common.Measurement.CourseTrueNorth', types.float64]
DateTimeSeconds_MIN = -9223372036854775807
DateTimeSeconds_MAX = 9223372036854775807
DateTimeSeconds = types.typedef['UMAA.Common.Measurement.DateTimeSeconds', types.int64]
DateTimeNanoseconds_MIN = 0
DateTimeNanoseconds_MAX = 999999999
DateTimeNanoseconds = types.typedef['UMAA.Common.Measurement.DateTimeNanoseconds', types.int32]

@dataclass
@annotate.final
@annotate.autoid("sequential")
class DateTime(idl.IdlStruct, typename="UMAA.Common.Measurement.DateTime"):
    seconds: 'UMAA.Common.Measurement.DateTimeSeconds'
    nanoseconds: 'UMAA.Common.Measurement.DateTimeNanoseconds'

Density_MIN = 0.000000
Density_MAX = 300000000000000000.000000
Density = types.typedef['UMAA.Common.Measurement.Density', types.float64]
Distance_MIN = 0.000000
Distance_MAX = 401056000.000000
Distance = types.typedef['UMAA.Common.Measurement.Distance', types.float64]
DurationHours_MIN = 0.000000
DurationHours_MAX = 10505.000000
DurationHours = types.typedef['UMAA.Common.Measurement.DurationHours', types.float64]
DurationSeconds_MIN = 0.000000
DurationSeconds_MAX = 37817280.000000
DurationSeconds = types.typedef['UMAA.Common.Measurement.DurationSeconds', types.float64]
ElectricalPower_MIN = 0.000000
ElectricalPower_MAX = 100000000.000000
ElectricalPower = types.typedef['UMAA.Common.Measurement.ElectricalPower', types.float64]
EngineSpeed_MIN = -100000.000000
EngineSpeed_MAX = 100000.000000
EngineSpeed = types.typedef['UMAA.Common.Measurement.EngineSpeed', types.float64]
Force_MIN = 0.000000
Force_MAX = 100000000.000000
Force = types.typedef['UMAA.Common.Measurement.Force', types.float64]
FrequencyHertz_MIN = 0.000000
FrequencyHertz_MAX = 10000000000.000000
FrequencyHertz = types.typedef['UMAA.Common.Measurement.FrequencyHertz', types.float64]
GroundSpeed_MIN = -299792458.000000
GroundSpeed_MAX = 299792458.000000
GroundSpeed = types.typedef['UMAA.Common.Measurement.GroundSpeed', types.float64]
HeadingTrueNorthAngle_MIN = -6.283185
HeadingTrueNorthAngle_MAX = 6.283185
HeadingTrueNorthAngle = types.typedef['UMAA.Common.Measurement.HeadingTrueNorthAngle', types.float64]
IndicatedAirspeed_MIN = 0.000000
IndicatedAirspeed_MAX = 299792458.000000
IndicatedAirspeed = types.typedef['UMAA.Common.Measurement.IndicatedAirspeed', types.float64]
MagneticVariation_MIN = -6.283185
MagneticVariation_MAX = 6.283185
MagneticVariation = types.typedef['UMAA.Common.Measurement.MagneticVariation', types.float64]
Mass_MIN = 0.000000
Mass_MAX = 100000000.000000
Mass = types.typedef['UMAA.Common.Measurement.Mass', types.float64]
NumericGUID = types.typedef['UMAA.Common.Measurement.NumericGUID', types.array[types.byte, 16]]
Percent_MIN = 0.000000
Percent_MAX = 1000.000000
Percent = types.typedef['UMAA.Common.Measurement.Percent', types.float64]
PitchHalfAngle_MIN = -1.570796
PitchHalfAngle_MAX = 1.570796
PitchHalfAngle = types.typedef['UMAA.Common.Measurement.PitchHalfAngle', types.float64]
PitchAcceleration_MIN = -10000.000000
PitchAcceleration_MAX = 10000.000000
PitchAcceleration = types.typedef['UMAA.Common.Measurement.PitchAcceleration', types.float64]
PitchRate_MIN = -32.767000
PitchRate_MAX = 32.767000
PitchRate = types.typedef['UMAA.Common.Measurement.PitchRate', types.float64]
PowerBusCurrent_MIN = -100000.000000
PowerBusCurrent_MAX = 100000.000000
PowerBusCurrent = types.typedef['UMAA.Common.Measurement.PowerBusCurrent', types.float64]
PowerBusVoltage_MIN = -100000.000000
PowerBusVoltage_MAX = 100000.000000
PowerBusVoltage = types.typedef['UMAA.Common.Measurement.PowerBusVoltage', types.float64]
PressureKiloPascals_MIN = 0.000000
PressureKiloPascals_MAX = 51200.000000
PressureKiloPascals = types.typedef['UMAA.Common.Measurement.PressureKiloPascals', types.float64]
PressurePascals_MIN = 0.000000
PressurePascals_MAX = 107558000.000000
PressurePascals = types.typedef['UMAA.Common.Measurement.PressurePascals', types.float64]
RadioFrequencyHertz_MIN = 0.000000
RadioFrequencyHertz_MAX = 10000000000.000000
RadioFrequencyHertz = types.typedef['UMAA.Common.Measurement.RadioFrequencyHertz', types.float64]
RelativeAngle_MIN = -6.283185
RelativeAngle_MAX = 6.283185
RelativeAngle = types.typedef['UMAA.Common.Measurement.RelativeAngle', types.float64]
RelativeHumidity_MIN = 0.000000
RelativeHumidity_MAX = 1000.000000
RelativeHumidity = types.typedef['UMAA.Common.Measurement.RelativeHumidity', types.float64]
RollAngle_MIN = -6.283185
RollAngle_MAX = 6.283185
RollAngle = types.typedef['UMAA.Common.Measurement.RollAngle', types.float64]
RollAcceleration_MIN = -10000.000000
RollAcceleration_MAX = 10000.000000
RollAcceleration = types.typedef['UMAA.Common.Measurement.RollAcceleration', types.float64]
RollRate_MIN = -32.767000
RollRate_MAX = 32.767000
RollRate = types.typedef['UMAA.Common.Measurement.RollRate', types.float64]
SizeBytes_MIN = 0
SizeBytes_MAX = 1000000000
SizeBytes = types.typedef['UMAA.Common.Measurement.SizeBytes', types.int32]
SizeReal = types.typedef['UMAA.Common.Measurement.SizeReal', types.float64]
Speed_MIN = 0.000000
Speed_MAX = 299792458.000000
Speed = types.typedef['UMAA.Common.Measurement.Speed', types.float64]
Temperature_MIN = -273.000000
Temperature_MAX = 1000.000000
Temperature = types.typedef['UMAA.Common.Measurement.Temperature', types.float64]
TurnRate_MIN = -32.767000
TurnRate_MAX = 32.767000
TurnRate = types.typedef['UMAA.Common.Measurement.TurnRate', types.float64]
YawAcceleration_MIN = -10000.000000
YawAcceleration_MAX = 10000.000000
YawAcceleration = types.typedef['UMAA.Common.Measurement.YawAcceleration', types.float64]
YawRate_MIN = -32.767000
YawRate_MAX = 32.767000
YawRate = types.typedef['UMAA.Common.Measurement.YawRate', types.float64]

