"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: Position3DBodyXYZ.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class Position3DBodyXYZ(idl.IdlStruct, typename="UMAA.Common.Measurement.Position3DBodyXYZ"):
    xAxis: 'UMAA.Common.PrimitiveConstrained.XPosition'
    yAxis: 'UMAA.Common.PrimitiveConstrained.YPosition'
    zAxis: 'UMAA.Common.PrimitiveConstrained.ZPosition'


