"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Measurement
  IDL file: RotationalEffort.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class RotationalEffort(idl.IdlStruct, typename="UMAA.Common.Measurement.RotationalEffort"):
    pitchEffort: 'UMAA.Common.Measurement.Effort'
    rollEffort: 'UMAA.Common.Measurement.Effort'
    yawEffort: 'UMAA.Common.Measurement.Effort'


