"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Enumeration.OnOffStatusEnumModule

"""

from ._EnumerationSets import OnOffStatusEnumType
__all__ = [
	"OnOffStatusEnumType",
]
