"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Enumeration.PrecipitationEnumModule
  IDL file: EnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class PrecipitationEnumType(idl.IdlEnum, typename="UMAA.Common.Enumeration.PrecipitationEnumModule.PrecipitationEnumType", default="DRIZZLE"):
    DRIZZLE = auto()
    FOG = auto()
    HAZE = auto()
    RAIN = auto()
    SHOWERS = auto()
    SNOW = auto()
    THUNDERSTORMS = auto()

