"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.MissionPlanAssignmentControl
  IDL file: MissionPlanAssignmentCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


MissionPlanAssignmentCommandAckReportTypeTopic = "UMAA::MM::MissionPlanAssignmentControl::MissionPlanAssignmentCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanAssignmentCommandAckReportType(idl.IdlStruct, typename="UMAA.MM.MissionPlanAssignmentControl.MissionPlanAssignmentCommandAckReportType"):
    command: 'UMAA.MM.MissionPlanAssignmentControl.MissionPlanAssignmentCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


