"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.TFOMEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class TFOMEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.TFOMEnumModule.TFOMEnumType", default="TFOM_1"):
    TFOM_1 = auto()
    TFOM_2 = auto()
    TFOM_3 = auto()
    TFOM_4 = auto()
    TFOM_5 = auto()
    TFOM_6 = auto()
    TFOM_7 = auto()
    TFOM_8 = auto()
    TFOM_9 = auto()

