"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.AnchorStatus
  IDL file: AnchorReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.AnchorStateEnumModule
    import UMAA.Common.Measurement


AnchorReportTypeTopic = "UMAA::EO::AnchorStatus::AnchorReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class AnchorReportType(idl.IdlStruct, typename="UMAA.EO.AnchorStatus.AnchorReportType"):
    rodeLengthPaidOut: 'UMAA.Common.Measurement.Distance'
    state: 'UMAA.Common.MaritimeEnumeration.AnchorStateEnumModule.AnchorStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


