"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.PassiveContactFeatureEnumModule

"""

from ._MaritimeEnumerationSets import PassiveContactFeatureEnumType
__all__ = [
	"PassiveContactFeatureEnumType",
]
