"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.PowerOnTestEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class PowerOnTestEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.PowerOnTestEnumModule.PowerOnTestEnumType", default="DISABLED_NO_TEST"):
    DISABLED_NO_TEST = auto()
    FULL_TEST = auto()
    QUICK_TEST = auto()

