"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ECEFPoseStatus
  IDL file: ECEFPoseReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation


ECEFPoseReportTypeTopic = "UMAA::SA::ECEFPoseStatus::ECEFPoseReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ECEFPoseReportType(idl.IdlStruct, typename="UMAA.SA.ECEFPoseStatus.ECEFPoseReportType"):
    attitude: 'UMAA.Common.Orientation.Orientation3DNEDType'
    attitudeCovariance: Optional['UMAA.Common.Measurement.CovarianceOrientationNEDType']
    positionCovariance: Optional['UMAA.Common.Measurement.CovariancePositionECEFType']
    xPosition: 'UMAA.Common.Measurement.Distance'
    yPosition: 'UMAA.Common.Measurement.Distance'
    zPosition: 'UMAA.Common.Measurement.Distance'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


