"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: AnnulusSectorRequirementType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class AnnulusSectorRequirementType(idl.IdlStruct, typename="UMAA.MM.BaseType.AnnulusSectorRequirementType"):
    annulusSectorTolerance: Optional['UMAA.MM.BaseType.AnnulusSectorToleranceType']
    maxRange: 'UMAA.Common.Measurement.Distance'
    minRange: 'UMAA.Common.Measurement.Distance'
    sector: 'UMAA.Common.Orientation.BearingSectorVariantType'


