"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: AreaRandomWalkObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.Speed


AreaRandomWalkObjectiveTypeTopic = "UMAA::MM::BaseType::AreaRandomWalkObjectiveType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class AreaRandomWalkObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.AreaRandomWalkObjectiveType"):
    area: 'UMAA.MM.BaseType.PolygonAreaRequirementType'
    duration: Optional['UMAA.Common.Measurement.DurationSeconds']
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    maxSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    maxTimeOnCourse: 'UMAA.Common.Measurement.DurationSeconds'
    minSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    minTimeOnCourse: 'UMAA.Common.Measurement.DurationSeconds'
    transitElevation: Optional['UMAA.Common.Measurement.ElevationVariantType']
    transitSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


