"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: DriftObjectiveDetailedStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


DriftObjectiveDetailedStatusTypeTopic = "UMAA::MM::BaseType::DriftObjectiveDetailedStatusType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class DriftObjectiveDetailedStatusType(idl.IdlStruct, typename="UMAA.MM.BaseType.DriftObjectiveDetailedStatusType"):
    distanceFromReference: 'UMAA.Common.Measurement.Distance'
    isDriftAchieved: bool
    isInPattern: bool
    isInPoweredDriving: bool
    referencePosition: 'UMAA.Common.Measurement.GeoPosition2D'
    timePatternAchieved: 'UMAA.Common.Measurement.DateTime'
    timePatternCompleted: Optional['UMAA.Common.Measurement.DateTime']
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


