"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: Figure8ObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Distance
    import UMAA.Common.MaritimeEnumeration.WaterTurnDirectionEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.Speed


Figure8ObjectiveTypeTopic = "UMAA::MM::BaseType::Figure8ObjectiveType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Figure8ObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.Figure8ObjectiveType"):
    duration: Optional['UMAA.Common.Measurement.DurationSeconds']
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    length: 'UMAA.Common.Measurement.Distance'
    loops: Optional['UMAA.Common.Measurement.SizeReal']
    orientation: 'UMAA.Common.Orientation.DirectionVariantType'
    position: Optional['UMAA.Common.Measurement.GeoPosition2D']
    radius: 'UMAA.Common.Measurement.Distance'
    speed: 'UMAA.Common.Speed.SpeedRequirementVariantType'
    trackTolerance: 'UMAA.Common.Distance.DistanceRequirementType'
    transitElevation: Optional['UMAA.Common.Measurement.ElevationVariantType']
    transitSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    turnDirection: 'UMAA.Common.MaritimeEnumeration.WaterTurnDirectionEnumModule.WaterTurnDirectionEnumType'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


