"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: HoverObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Distance
    import UMAA.Common.MaritimeEnumeration.HoverKindEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.Speed


HoverObjectiveTypeTopic = "UMAA::MM::BaseType::HoverObjectiveType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class HoverObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.HoverObjectiveType"):
    controlPriority: 'UMAA.Common.MaritimeEnumeration.HoverKindEnumModule.HoverKindEnumType'
    duration: Optional['UMAA.Common.Measurement.DurationSeconds']
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    heading: Optional['UMAA.Common.Orientation.DirectionRequirementVariantType']
    hoverRadius: 'UMAA.Common.Distance.DistanceRequirementType'
    position: Optional['UMAA.Common.Measurement.GeoPosition2D']
    transitElevation: Optional['UMAA.Common.Measurement.ElevationVariantType']
    transitSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


