"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: HoverObjectiveDetailedStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation


HoverObjectiveDetailedStatusTypeTopic = "UMAA::MM::BaseType::HoverObjectiveDetailedStatusType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class HoverObjectiveDetailedStatusType(idl.IdlStruct, typename="UMAA.MM.BaseType.HoverObjectiveDetailedStatusType"):
    hoverHeading: 'UMAA.Common.Orientation.DirectionVariantType'
    hoverPosition: 'UMAA.Common.Measurement.GeoPosition2D'
    isHoverHeadingAchieved: bool
    isHoverPositionAchieved: bool
    isInPattern: bool
    timePatternAchieved: 'UMAA.Common.Measurement.DateTime'
    timePatternCompleted: Optional['UMAA.Common.Measurement.DateTime']
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


