"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: ObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class ObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.ObjectiveType"):
    approvalRequired: bool
    duringConditionID: Optional['UMAA.Common.Measurement.NumericGUID']
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    objectiveDescription: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    objectiveID: 'UMAA.Common.Measurement.NumericGUID'
    objectivePriority: 'UMAA.Common.Measurement.Priority'
    preconditionID: Optional['UMAA.Common.Measurement.NumericGUID']
    preferredResourceID: types.sequence['UMAA.Common.IdentifierType', 16]
    stateTrigger: types.sequence['UMAA.MM.BaseType.StateTriggerType', 16]
    specializationID: 'UMAA.Common.Measurement.NumericGUID'
    specializationTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationTopic: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'


