"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: ObjectiveDetailedStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateEnumModule
    import UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateReasonEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class ObjectiveDetailedStatusType(idl.IdlStruct, typename="UMAA.MM.BaseType.ObjectiveDetailedStatusType"):
    childObjectiveIDs: types.sequence['UMAA.Common.Measurement.NumericGUID', 256]
    errors: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    feedback: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    isCurrentlyMeetingObjective: bool
    objectiveID: 'UMAA.Common.Measurement.NumericGUID'
    objectiveStatus: 'UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateEnumModule.ObjectiveExecutorStateEnumType'
    objectiveStatusReason: 'UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateReasonEnumModule.ObjectiveExecutorStateReasonEnumType'
    startTime: 'UMAA.Common.Measurement.DateTime'
    warnings: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    specializationID: 'UMAA.Common.Measurement.NumericGUID'
    specializationTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationTopic: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'


