"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: PolygonVariantType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Enumeration.LineSegmentEnumModule
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class PolygonVariantType(idl.IdlStruct, typename="UMAA.MM.BaseType.PolygonVariantType"):
    lineKind: 'UMAA.Common.Enumeration.LineSegmentEnumModule.LineSegmentEnumType'
    referencePoints: types.sequence['UMAA.Common.Measurement.GeoPosition2D', 128]


