"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: RecoveryObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.Position


RecoveryObjectiveTypeTopic = "UMAA::MM::BaseType::RecoveryObjectiveType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class RecoveryObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.RecoveryObjectiveType"):
    elevation: 'UMAA.Common.Measurement.ElevationVariantType'
    position: 'UMAA.Common.Position.GeoPosition2DRequirement'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


