"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: RouteObjectiveType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


RouteObjectiveTypeTopic = "UMAA::MM::BaseType::RouteObjectiveType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class RouteObjectiveType(idl.IdlStruct, typename="UMAA.MM.BaseType.RouteObjectiveType"):
    routeDescription: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")
    waypointsListMetadata: 'UMAA.Common.LargeListMetadata'

RouteObjectiveTypeWaypointsListElementTopic = "UMAA::MM::BaseType::RouteObjectiveTypeWaypointsListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class RouteObjectiveTypeWaypointsListElement(idl.IdlStruct, typename="UMAA.MM.BaseType.RouteObjectiveTypeWaypointsListElement"):
    element: 'UMAA.MM.BaseType.WaypointType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']


