"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: StationkeepObjectiveDetailedStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


StationkeepObjectiveDetailedStatusTypeTopic = "UMAA::MM::BaseType::StationkeepObjectiveDetailedStatusType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class StationkeepObjectiveDetailedStatusType(idl.IdlStruct, typename="UMAA.MM.BaseType.StationkeepObjectiveDetailedStatusType"):
    bearingGuide: Optional['UMAA.Common.Measurement.HeadingTarget']
    bearingMagneticNorth: Optional['UMAA.Common.Measurement.HeadingMagneticNorth']
    bearingTrueNorth: Optional['UMAA.Common.Measurement.HeadingTrueNorthAngle']
    closingSpeed: 'UMAA.Common.Measurement.GroundSpeed'
    distanceFromTrack: 'UMAA.Common.Measurement.Distance'
    guideLost: bool
    isAreaAchieved: bool
    isInPattern: bool
    timePatternAchieved: 'UMAA.Common.Measurement.DateTime'
    timePatternCompleted: Optional['UMAA.Common.Measurement.DateTime']
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


