"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: TaskPlanType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class TaskPlanType(idl.IdlStruct, typename="UMAA.MM.BaseType.TaskPlanType"):
    approvalRequired: bool
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    stateTrigger: types.sequence['UMAA.MM.BaseType.StateTriggerType', 16]
    taskDescription: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    taskID: 'UMAA.Common.Measurement.NumericGUID'
    taskPriority: 'UMAA.Common.Measurement.Priority'
    objectivesSetMetadata: 'UMAA.Common.LargeSetMetadata'

TaskPlanTypeObjectivesSetElementTopic = "UMAA::MM::BaseType::TaskPlanTypeObjectivesSetElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TaskPlanTypeObjectivesSetElement(idl.IdlStruct, typename="UMAA.MM.BaseType.TaskPlanTypeObjectivesSetElement"):
    element: 'UMAA.MM.BaseType.ObjectiveType'
    setID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("setID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'


