"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.BaseType
  IDL file: WaypointDetailedStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.WaypointStateEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class WaypointDetailedStatusType(idl.IdlStruct, typename="UMAA.MM.BaseType.WaypointDetailedStatusType"):
    avgCrossTrackError: Optional['UMAA.Common.Measurement.Distance']
    avgSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    errors: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    feedback: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    maxCrossTrackError: Optional['UMAA.Common.Measurement.Distance']
    maxSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    state: 'UMAA.Common.MaritimeEnumeration.WaypointStateEnumModule.WaypointStateEnumType'
    warnings: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    waypointID: 'UMAA.Common.Measurement.NumericGUID'


