"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.TaskPlanExecutionControl
  IDL file: TaskPlanExecutionCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.TaskControlEnumModule
    import UMAA.Common.Measurement


TaskPlanExecutionCommandTypeTopic = "UMAA::MM::TaskPlanExecutionControl::TaskPlanExecutionCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TaskPlanExecutionCommandType(idl.IdlStruct, typename="UMAA.MM.TaskPlanExecutionControl.TaskPlanExecutionCommandType"):
    missionID: 'UMAA.Common.Measurement.NumericGUID'
    state: 'UMAA.Common.MaritimeEnumeration.TaskControlEnumModule.TaskControlEnumType'
    taskID: Optional['UMAA.Common.Measurement.NumericGUID']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


