"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.IlluminatorControl
  IDL file: IlluminatorCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.IlluminatorStateEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained
    import UMAA.SEM.BaseType


IlluminatorCommandTypeTopic = "UMAA::SEM::IlluminatorControl::IlluminatorCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class IlluminatorCommandType(idl.IdlStruct, typename="UMAA.SEM.IlluminatorControl.IlluminatorCommandType"):
    beamWidth: Optional['UMAA.Common.PrimitiveConstrained.IlluminatorBeamWidth']
    color: Optional['UMAA.SEM.BaseType.RGBType']
    intensity: Optional['UMAA.Common.PrimitiveConstrained.IlluminatorIntensityLevel']
    state: 'UMAA.Common.MaritimeEnumeration.IlluminatorStateEnumModule.IlluminatorStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


