"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WeatherStatus

"""

from ._WeatherReportType import WeatherReportType, WeatherReportTypeTopic
__all__ = [
	"WeatherReportType",
	"WeatherReportTypeTopic",
]
