"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WeatherStatus
  IDL file: WeatherReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Enumeration.PrecipitationEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.OrderedEnumeration.CloudCoverEnumModule
    import UMAA.Common.OrderedEnumeration.WeatherSeverityEnumModule
    import UMAA.Common.PrimitiveConstrained


WeatherReportTypeTopic = "UMAA::SA::WeatherStatus::WeatherReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class WeatherReportType(idl.IdlStruct, typename="UMAA.SA.WeatherStatus.WeatherReportType"):
    airTemperature: Optional['UMAA.Common.PrimitiveConstrained.AirTemperature']
    barometricPressure: Optional['UMAA.Common.PrimitiveConstrained.WeatherBarometricPressure']
    cloudiness: Optional['UMAA.Common.OrderedEnumeration.CloudCoverEnumModule.CloudCoverEnumType']
    dewPoint: Optional['UMAA.Common.PrimitiveConstrained.DewPointTemperature']
    icingSeverity: Optional['UMAA.Common.OrderedEnumeration.WeatherSeverityEnumModule.WeatherSeverityEnumType']
    precipitation: Optional['UMAA.Common.Enumeration.PrecipitationEnumModule.PrecipitationEnumType']
    relativeHumidity: Optional['UMAA.Common.Measurement.Percent']
    thunderstormPotential: Optional['UMAA.Common.Measurement.Percent']
    visibility: Optional['UMAA.Common.Measurement.Distance']
    waterTemperature: Optional['UMAA.Common.PrimitiveConstrained.WaterTemperature']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


