"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.GPSStatus
  IDL file: GPSSatelliteType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.GPSConstellationEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GPSSatelliteType(idl.IdlStruct, typename="UMAA.SEM.GPSStatus.GPSSatelliteType"):
    antennaCarrierNoiseDensity: 'UMAA.Common.PrimitiveConstrained.CarrierToNoiseDensityRatio'
    azimuth: 'UMAA.Common.Measurement.Angle'
    basebandCarrierNoiseDensity: 'UMAA.Common.PrimitiveConstrained.CarrierToNoiseDensityRatio'
    carrierFrequency: 'UMAA.Common.Measurement.RadioFrequencyHertz'
    constellationType: 'UMAA.Common.MaritimeEnumeration.GPSConstellationEnumModule.GPSConstellationEnumType'
    containsAlmanacData: bool
    elevation: 'UMAA.Common.Measurement.Angle'
    ephemerisData: bool
    satelliteID: 'UMAA.Common.PrimitiveConstrained.NaturalNumberCount'
    usedInFix: bool


