"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.HazardAvoidanceConfig
  IDL file: HazardAvoidanceConfigReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


HazardAvoidanceConfigReportTypeTopic = "UMAA::MO::HazardAvoidanceConfig::HazardAvoidanceConfigReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class HazardAvoidanceConfigReportType(idl.IdlStruct, typename="UMAA.MO.HazardAvoidanceConfig.HazardAvoidanceConfigReportType"):
    hazardAvoidanceConfig: Optional['UMAA.MO.HazardAvoidanceConfig.ContactHazardAvoidanceType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")


