"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Position

"""

from ._GeoPosition2DRequirement import GeoPosition2DRequirement
from ._GeoPosition2DTolerance import GeoPosition2DTolerance
__all__ = [
	"GeoPosition2DRequirement",
	"GeoPosition2DTolerance",
]
