"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactCOLREGSClassificationStatus

"""

from ._ContactCOLREGSClassificationReportType import ContactCOLREGSClassificationReportType, ContactCOLREGSClassificationReportTypeTopic
__all__ = [
	"ContactCOLREGSClassificationReportType",
	"ContactCOLREGSClassificationReportTypeTopic",
]
