"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactCOLREGSClassificationStatus
  IDL file: ContactCOLREGSClassificationReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.COLREGSClassificationEnumModule
    import UMAA.Common.Measurement


ContactCOLREGSClassificationReportTypeTopic = "UMAA::SA::ContactCOLREGSClassificationStatus::ContactCOLREGSClassificationReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactCOLREGSClassificationReportType(idl.IdlStruct, typename="UMAA.SA.ContactCOLREGSClassificationStatus.ContactCOLREGSClassificationReportType"):
    confidence: 'UMAA.Common.Measurement.Percent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    colregsClassification: 'UMAA.Common.MaritimeEnumeration.COLREGSClassificationEnumModule.COLREGSClassificationEnumType'
    annotate.key("colregsClassification")
    contactID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("contactID")


