"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.PowerStatus
  IDL file: PowerReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.PowerStateEnumModule
    import UMAA.Common.Measurement


PowerReportTypeTopic = "UMAA::EO::PowerStatus::PowerReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PowerReportType(idl.IdlStruct, typename="UMAA.EO.PowerStatus.PowerReportType"):
    state: 'UMAA.Common.MaritimeEnumeration.PowerStateEnumModule.PowerStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    resourceID: 'UMAA.Common.IdentifierType'
    annotate.key("resourceID")


