"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.TamperDetectionStatus
  IDL file: TamperDetectionReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.TamperDetectionStateEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


TamperDetectionReportTypeTopic = "UMAA::SO::TamperDetectionStatus::TamperDetectionReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TamperDetectionReportType(idl.IdlStruct, typename="UMAA.SO.TamperDetectionStatus.TamperDetectionReportType"):
    descriptor: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    electricalTamper: bool
    hardwareTamper: bool
    networkInstrusion: bool
    otherTamper: bool
    state: 'UMAA.Common.MaritimeEnumeration.TamperDetectionStateEnumModule.TamperDetectionStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


