"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.MissionPlanConstraintControl
  IDL file: MissionPlanConstraintDeleteCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


MissionPlanConstraintDeleteCommandTypeTopic = "UMAA::MM::MissionPlanConstraintControl::MissionPlanConstraintDeleteCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanConstraintDeleteCommandType(idl.IdlStruct, typename="UMAA.MM.MissionPlanConstraintControl.MissionPlanConstraintDeleteCommandType"):
    constraintID: Optional['UMAA.Common.Measurement.NumericGUID']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


