"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.GeneratorSpecs

"""

from ._GeneratorSpecsReportType import GeneratorSpecsReportType, GeneratorSpecsReportTypeTopic
__all__ = [
	"GeneratorSpecsReportType",
	"GeneratorSpecsReportTypeTopic",
]
