"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.GeneratorSpecs
  IDL file: GeneratorSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


GeneratorSpecsReportTypeTopic = "UMAA::EO::GeneratorSpecs::GeneratorSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GeneratorSpecsReportType(idl.IdlStruct, typename="UMAA.EO.GeneratorSpecs.GeneratorSpecsReportType"):
    maxCurrent: 'UMAA.Common.Measurement.PowerBusCurrent'
    maxPower: 'UMAA.Common.Measurement.ElectricalPower'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    ratedPower: 'UMAA.Common.Measurement.ElectricalPower'
    ratedVoltage: 'UMAA.Common.Measurement.PowerBusVoltage'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


