"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.EmitterControl
  IDL file: EmitterCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


EmitterCommandAckReportTypeTopic = "UMAA::SO::EmitterControl::EmitterCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EmitterCommandAckReportType(idl.IdlStruct, typename="UMAA.SO.EmitterControl.EmitterCommandAckReportType"):
    command: 'UMAA.SO.EmitterControl.EmitterCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


