"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceIdentification

"""

from ._ResourceAuthorizationReportType import ResourceAuthorizationReportType, ResourceAuthorizationReportTypeTopic
from ._SubsystemIDReportType import SubsystemIDReportType, SubsystemIDReportTypeTopic
from ._VehicleIDReportType import VehicleIDReportType, VehicleIDReportTypeTopic
__all__ = [
	"ResourceAuthorizationReportType",
	"ResourceAuthorizationReportTypeTopic",
	"SubsystemIDReportType",
	"SubsystemIDReportTypeTopic",
	"VehicleIDReportType",
	"VehicleIDReportTypeTopic",
]
