"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceIdentification
  IDL file: ResourceAuthorizationReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Enumeration.SpecificLOIEnumModule
    import UMAA.Common.Measurement


ResourceAuthorizationReportTypeTopic = "UMAA::SO::ResourceIdentification::ResourceAuthorizationReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ResourceAuthorizationReportType(idl.IdlStruct, typename="UMAA.SO.ResourceIdentification.ResourceAuthorizationReportType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    authorizationLevel: 'UMAA.Common.Enumeration.SpecificLOIEnumModule.SpecificLOIEnumType'
    annotate.key("authorizationLevel")


