"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceIdentification
  IDL file: SubsystemIDReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


SubsystemIDReportTypeTopic = "UMAA::SO::ResourceIdentification::SubsystemIDReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class SubsystemIDReportType(idl.IdlStruct, typename="UMAA.SO.ResourceIdentification.SubsystemIDReportType"):
    isControlTransferCapable: bool
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    type: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


