"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceIdentification
  IDL file: VehicleIDReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.DomainEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


VehicleIDReportTypeTopic = "UMAA::SO::ResourceIdentification::VehicleIDReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class VehicleIDReportType(idl.IdlStruct, typename="UMAA.SO.ResourceIdentification.VehicleIDReportType"):
    domain: 'UMAA.Common.MaritimeEnumeration.DomainEnumModule.DomainEnumType'
    isControlTransferCapable: bool
    make: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    model: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    protocol: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    type: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    vehicleNumber: 'UMAA.Common.IdentifierType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


