"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: ConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class ConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.ConditionalType"):
    conditionalID: 'UMAA.Common.Measurement.NumericGUID'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    specializationID: 'UMAA.Common.Measurement.NumericGUID'
    specializationTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationTopic: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'


