"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: ConstraintViolatedConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


ConstraintViolatedConditionalTypeTopic = "UMAA::MM::Conditional::ConstraintViolatedConditionalType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ConstraintViolatedConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.ConstraintViolatedConditionalType"):
    constraintConditionalID: 'UMAA.Common.Measurement.NumericGUID'
    duration: Optional['UMAA.Common.Measurement.DurationSeconds']
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


