"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: HeadingSectorType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.HeadingSectorKindEnumModule
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class HeadingSectorType(idl.IdlStruct, typename="UMAA.MM.Conditional.HeadingSectorType"):
    endHeading: 'UMAA.Common.Measurement.YawAngle'
    headingSectorKind: 'UMAA.Common.MaritimeEnumeration.HeadingSectorKindEnumModule.HeadingSectorKindEnumType'
    startHeading: 'UMAA.Common.Measurement.YawAngle'


