"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: LogicalORConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


LogicalORConditionalTypeTopic = "UMAA::MM::Conditional::LogicalORConditionalType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LogicalORConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.LogicalORConditionalType"):
    conditionalID1: 'UMAA.Common.Measurement.NumericGUID'
    conditionalID2: 'UMAA.Common.Measurement.NumericGUID'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


