"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: LogicalNOTConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


LogicalNOTConditionalTypeTopic = "UMAA::MM::Conditional::LogicalNOTConditionalType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LogicalNOTConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.LogicalNOTConditionalType"):
    notConditionalID: 'UMAA.Common.Measurement.NumericGUID'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


