"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: TimeConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.ConditionalOperatorEnumModule
    import UMAA.Common.Measurement


TimeConditionalTypeTopic = "UMAA::MM::Conditional::TimeConditionalType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TimeConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.TimeConditionalType"):
    conditionalOp: 'UMAA.Common.MaritimeEnumeration.ConditionalOperatorEnumModule.ConditionalOperatorEnumType'
    time: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


