"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.Conditional
  IDL file: WaterZoneConditionalType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.WaterZoneKindEnumModule
    import UMAA.Common.Measurement
    import UMAA.MM.BaseType


WaterZoneConditionalTypeTopic = "UMAA::MM::Conditional::WaterZoneConditionalType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class WaterZoneConditionalType(idl.IdlStruct, typename="UMAA.MM.Conditional.WaterZoneConditionalType"):
    ceiling: 'UMAA.Common.Measurement.ElevationVariantType'
    floor: 'UMAA.Common.Measurement.ElevationVariantType'
    zone: types.sequence['UMAA.MM.BaseType.ShapeVariantType', 16]
    zoneKind: 'UMAA.Common.MaritimeEnumeration.WaterZoneKindEnumModule.WaterZoneKindEnumType'
    specializationReferenceTimestamp: 'UMAA.Common.Measurement.DateTime'
    specializationReferenceID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("specializationReferenceID")


