"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.HandoverResultEnumModule

"""

from ._MaritimeEnumerationSets import HandoverResultEnumType
__all__ = [
	"HandoverResultEnumType",
]
