"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.AutoOffModeEnumModule

"""

from ._MaritimeEnumerationSets import AutoOffModeEnumType
__all__ = [
	"AutoOffModeEnumType",
]
