"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.AutoOffModeEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class AutoOffModeEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.AutoOffModeEnumModule.AutoOffModeEnumType", default="DEACTIVATE"):
    DEACTIVATE = auto()
    SHUTDOWN = auto()

