"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalHoverControl
  IDL file: GlobalHoverCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


GlobalHoverCommandAckReportTypeTopic = "UMAA::MO::GlobalHoverControl::GlobalHoverCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalHoverCommandAckReportType(idl.IdlStruct, typename="UMAA.MO.GlobalHoverControl.GlobalHoverCommandAckReportType"):
    command: 'UMAA.MO.GlobalHoverControl.GlobalHoverCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


