"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.IgnitionStateEnumModule

"""

from ._MaritimeEnumerationSets import IgnitionStateEnumType
__all__ = [
	"IgnitionStateEnumType",
]
