"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.OperationalModeControl
  IDL file: OperationalModeCommandAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


OperationalModeCommandAckReportTypeTopic = "UMAA::MM::OperationalModeControl::OperationalModeCommandAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class OperationalModeCommandAckReportType(idl.IdlStruct, typename="UMAA.MM.OperationalModeControl.OperationalModeCommandAckReportType"):
    command: 'UMAA.MM.OperationalModeControl.OperationalModeCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


