"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.CoordinationSituationalSignalStatus
  IDL file: CoordinationSituationalSignalReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.CoordinationSituationalSignalEnumModule
    import UMAA.Common.Measurement


CoordinationSituationalSignalReportTypeTopic = "UMAA::MO::CoordinationSituationalSignalStatus::CoordinationSituationalSignalReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CoordinationSituationalSignalReportType(idl.IdlStruct, typename="UMAA.MO.CoordinationSituationalSignalStatus.CoordinationSituationalSignalReportType"):
    currentSituation: 'UMAA.Common.MaritimeEnumeration.CoordinationSituationalSignalEnumModule.CoordinationSituationalSignalEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


