"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.HoverKindEnumModule

"""

from ._MaritimeEnumerationSets import HoverKindEnumType
__all__ = [
	"HoverKindEnumType",
]
