"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.TaskStateEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class TaskStateEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.TaskStateEnumModule.TaskStateEnumType", default="AWAITING_EXECUTION_APPROVAL"):
    AWAITING_EXECUTION_APPROVAL = auto()
    CANCELED = auto()
    CANCELING = auto()
    COMPLETED = auto()
    EXECUTING = auto()
    EXECUTION_APPROVED = auto()
    FAILED = auto()
    NOT_PLANNED = auto()
    NOT_QUEUED = auto()
    PAUSED = auto()
    PAUSING = auto()
    PLANNED = auto()
    PLANNING = auto()
    QUEUED = auto()
    QUEUING = auto()
    RESTARTING = auto()
    RESUMING = auto()

