"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.MastStatus
  IDL file: MastReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.MastStateEnumModule
    import UMAA.Common.Measurement


MastReportTypeTopic = "UMAA::EO::MastStatus::MastReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MastReportType(idl.IdlStruct, typename="UMAA.EO.MastStatus.MastReportType"):
    state: 'UMAA.Common.MaritimeEnumeration.MastStateEnumModule.MastStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


