"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.FileSystemStatus
  IDL file: FileSystemReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


FileSystemReportTypeTopic = "UMAA::SO::FileSystemStatus::FileSystemReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class FileSystemReportType(idl.IdlStruct, typename="UMAA.SO.FileSystemStatus.FileSystemReportType"):
    availableInodes: Optional['UMAA.Common.Measurement.LargeCount']
    availableSpace: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    freeInodes: Optional['UMAA.Common.Measurement.LargeCount']
    freeSpace: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    inodes: Optional['UMAA.Common.Measurement.LargeCount']
    maxFilenameLength: Optional['UMAA.Common.Measurement.Count']
    path: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    reachable: bool
    readOnly: Optional[bool]
    totalSpace: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


