"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.FuelTankSpecs

"""

from ._FuelTankSpecsReportType import FuelTankSpecsReportType, FuelTankSpecsReportTypeTopic
__all__ = [
	"FuelTankSpecsReportType",
	"FuelTankSpecsReportTypeTopic",
]
