"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelStatus
  IDL file: CommsChannelReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.CommsChannelOperationalStatusEnumModule
    import UMAA.Common.Measurement


CommsChannelReportTypeTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelStatus.CommsChannelReportType"):
    channelOperationalStatus: 'UMAA.Common.MaritimeEnumeration.CommsChannelOperationalStatusEnumModule.CommsChannelOperationalStatusEnumType'
    downTime: Optional['UMAA.Common.Measurement.DurationSeconds']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


