"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelStatus
  IDL file: CommsChannelReceiverStatisticsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.CO.CommsChannel
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelReceiverStatisticsReportTypeTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReceiverStatisticsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelReceiverStatisticsReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelStatus.CommsChannelReceiverStatisticsReportType"):
    receiverStatistics: types.sequence['UMAA.CO.CommsChannel.CommsChannelReceiverStatisticsType', 256]
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


