"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelStatus
  IDL file: CommsChannelReceiverReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


CommsChannelReceiverReportTypeTopic = "UMAA::CO::CommsChannelStatus::CommsChannelReceiverReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelReceiverReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelStatus.CommsChannelReceiverReportType"):
    messageSize: 'UMAA.Common.Measurement.SizeBytes'
    messageSNR: 'UMAA.Common.PrimitiveConstrained.SignalToNoiseRatio'
    messageTime: 'UMAA.Common.Measurement.DateTime'
    messageType: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    messageID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("messageID")


