"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelStatus
  IDL file: CommsChannelSenderReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.CO.CommsChannel
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelSenderReportTypeTopic = "UMAA::CO::CommsChannelStatus::CommsChannelSenderReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelSenderReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelStatus.CommsChannelSenderReportType"):
    bufferPercentFull: 'UMAA.Common.Measurement.Percent'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    queuedMessagesListMetadata: 'UMAA.Common.LargeListMetadata'

CommsChannelSenderReportTypeQueuedMessagesListElementTopic = "UMAA::CO::CommsChannelStatus::CommsChannelSenderReportTypeQueuedMessagesListElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelSenderReportTypeQueuedMessagesListElement(idl.IdlStruct, typename="UMAA.CO.CommsChannelStatus.CommsChannelSenderReportTypeQueuedMessagesListElement"):
    element: 'UMAA.CO.CommsChannel.CommsChannelMessageType'
    listID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("listID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'
    nextElementID: Optional['UMAA.Common.Measurement.NumericGUID']


