"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MeasurementCoordinate

"""

from ._EngineeringCoordinateAxes import Down, DownSpeed, DownSpeed_MAX, DownSpeed_MIN, Down_MAX, Down_MIN, EastSpeed, EastSpeed_MAX, EastSpeed_MIN, Forward, Forward_MAX, Forward_MIN, NorthSpeed, NorthSpeed_MAX, NorthSpeed_MIN
from ._GeographicCoordinateAxes import GeodeticLatitude, GeodeticLatitude_MAX, GeodeticLatitude_MIN, GeodeticLongitude, GeodeticLongitude_MAX, GeodeticLongitude_MIN
__all__ = [
	"Down",
	"DownSpeed",
	"DownSpeed_MAX",
	"DownSpeed_MIN",
	"Down_MAX",
	"Down_MIN",
	"EastSpeed",
	"EastSpeed_MAX",
	"EastSpeed_MIN",
	"Forward",
	"Forward_MAX",
	"Forward_MIN",
	"NorthSpeed",
	"NorthSpeed_MAX",
	"NorthSpeed_MIN",
	"GeodeticLatitude",
	"GeodeticLatitude_MAX",
	"GeodeticLatitude_MIN",
	"GeodeticLongitude",
	"GeodeticLongitude_MAX",
	"GeodeticLongitude_MIN",
]
