"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MeasurementCoordinate
  IDL file: EngineeringCoordinateAxes.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

Down_MIN = -50000.000000
Down_MAX = 50000.000000
Down = types.typedef['UMAA.Common.MeasurementCoordinate.Down', types.float64]
DownSpeed_MIN = -299792458.000000
DownSpeed_MAX = 299792458.000000
DownSpeed = types.typedef['UMAA.Common.MeasurementCoordinate.DownSpeed', types.float64]
EastSpeed_MIN = -299792458.000000
EastSpeed_MAX = 299792458.000000
EastSpeed = types.typedef['UMAA.Common.MeasurementCoordinate.EastSpeed', types.float64]
Forward_MIN = -20000000.000000
Forward_MAX = 20000000.000000
Forward = types.typedef['UMAA.Common.MeasurementCoordinate.Forward', types.float64]
NorthSpeed_MIN = -299792458.000000
NorthSpeed_MAX = 299792458.000000
NorthSpeed = types.typedef['UMAA.Common.MeasurementCoordinate.NorthSpeed', types.float64]

