"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MeasurementCoordinate
  IDL file: GeographicCoordinateAxes.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

GeodeticLatitude_MIN = -90.000000
GeodeticLatitude_MAX = 90.000000
GeodeticLatitude = types.typedef['UMAA.Common.MeasurementCoordinate.GeodeticLatitude', types.float64]
GeodeticLongitude_MIN = -180.000000
GeodeticLongitude_MAX = 180.000000
GeodeticLongitude = types.typedef['UMAA.Common.MeasurementCoordinate.GeodeticLongitude', types.float64]

