"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ProcessingUnitEnumModule

"""

from ._MaritimeEnumerationSets import ProcessingUnitEnumType
__all__ = [
	"ProcessingUnitEnumType",
]
