"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ProcessingUnitEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ProcessingUnitEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ProcessingUnitEnumModule.ProcessingUnitEnumType", default="CPU"):
    CPU = auto()
    DSP = auto()
    FPGA = auto()
    GPU = auto()
    NPU = auto()
    PhPU = auto()
    PPU = auto()
    QPU = auto()
    SPU = auto()
    TPU = auto()
    VPU = auto()

