"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.EngineSpecs

"""

from ._EngineSpecsReportType import EngineSpecsReportType, EngineSpecsReportTypeTopic
__all__ = [
	"EngineSpecsReportType",
	"EngineSpecsReportTypeTopic",
]
