"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.EngineSpecs
  IDL file: EngineSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.EngineKindEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


EngineSpecsReportTypeTopic = "UMAA::EO::EngineSpecs::EngineSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EngineSpecsReportType(idl.IdlStruct, typename="UMAA.EO.EngineSpecs.EngineSpecsReportType"):
    engineKind: 'UMAA.Common.MaritimeEnumeration.EngineKindEnumModule.EngineKindEnumType'
    glowPlugTime: Optional['UMAA.Common.Measurement.DurationSeconds']
    maxCoolantLevel: 'UMAA.Common.Measurement.VolumeCubicMeter'
    maxCoolantPressure: 'UMAA.Common.Measurement.PressureKiloPascals'
    maxCoolantTemp: 'UMAA.Common.Measurement.Temperature'
    maxEngineTemp: 'UMAA.Common.Measurement.Temperature'
    maxGlowPlugTemp: Optional['UMAA.Common.Measurement.Temperature']
    maxManifoldAirTemp: 'UMAA.Common.Measurement.Temperature'
    maxManifoldPressure: 'UMAA.Common.Measurement.PressureKiloPascals'
    maxOilPressure: 'UMAA.Common.PrimitiveConstrained.MaxEngineOilPressure'
    maxOilTemp: 'UMAA.Common.Measurement.Temperature'
    minCoolantLevel: 'UMAA.Common.Measurement.VolumeCubicMeter'
    minOilLevel: 'UMAA.Common.Measurement.VolumeCubicMeter'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    oilCapacity: 'UMAA.Common.Measurement.VolumeCubicMeter'
    reverseRPMLowerLimit: 'UMAA.Common.Measurement.EngineSpeed'
    reverseRPMMaxLimit: 'UMAA.Common.Measurement.EngineSpeed'
    reverseRPMUpperLimit: 'UMAA.Common.Measurement.EngineSpeed'
    reversible: bool
    RPMLowerLimit: 'UMAA.Common.Measurement.EngineSpeed'
    RPMMaxLimit: 'UMAA.Common.Measurement.EngineSpeed'
    RPMUpperLimit: 'UMAA.Common.Measurement.EngineSpeed'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


