"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.VisualClassificationEnumModule

"""

from ._MaritimeEnumerationSets import VisualClassificationEnumType
__all__ = [
	"VisualClassificationEnumType",
]
