"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.VisualClassificationEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class VisualClassificationEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.VisualClassificationEnumModule.VisualClassificationEnumType", default="AID_TO_NAVIGATION_CHANNEL_MARKER"):
    AID_TO_NAVIGATION_CHANNEL_MARKER = auto()
    AID_TO_NAVIGATION_GENERAL = auto()
    AID_TO_NAVIGATION_LARGE_BUOY = auto()
    AID_TO_NAVIGATION_LIGHTHOUSE = auto()
    AID_TO_NAVIGATION_SMALL_BUOY = auto()
    LARGE_GENERAL_OBSTACLE = auto()
    LARGE_VESSEL_CARGO = auto()
    LARGE_VESSEL_GENERAL = auto()
    LARGE_VESSEL_MILITARY = auto()
    LARGE_VESSEL_OTHER = auto()
    LARGE_VESSEL_PASSENGER = auto()
    MEDIUM_VESSEL_FISHING = auto()
    MEDIUM_VESSEL_GENERAL = auto()
    MEDIUM_VESSEL_MILITARY = auto()
    MEDIUM_VESSEL_OTHER = auto()
    MEDIUM_VESSEL_TUG = auto()
    MEDIUM_VESSEL_TUG_IN_TOW = auto()
    MEDIUM_VESSEL_YACHT = auto()
    SAILBOAT = auto()
    SMALL_GENERAL_OBSTACLE = auto()
    SMALL_VESSEL_GENERAL = auto()
    SMALL_VESSEL_JET_SKI = auto()
    SMALL_VESSEL_MILITARY = auto()
    SMALL_VESSEL_OTHER = auto()
    SMALL_VESSEL_POWER_BOAT = auto()

