"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.HealthReport
  IDL file: HealthReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.ErrorCodeEnumModule
    import UMAA.Common.MaritimeEnumeration.ErrorConditionEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


HealthReportTypeTopic = "UMAA::SO::HealthReport::HealthReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class HealthReportType(idl.IdlStruct, typename="UMAA.SO.HealthReport.HealthReportType"):
    logTime: 'UMAA.Common.Measurement.DateTime'
    severity: 'UMAA.Common.MaritimeEnumeration.ErrorConditionEnumModule.ErrorConditionEnumType'
    status: Optional['UMAA.Common.PrimitiveConstrained.StringLongDescription']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    code: 'UMAA.Common.MaritimeEnumeration.ErrorCodeEnumModule.ErrorCodeEnumType'
    annotate.key("code")
    resourceID: 'UMAA.Common.IdentifierType'
    annotate.key("resourceID")


