"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Enumeration.LineSegmentEnumModule
  IDL file: EnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class LineSegmentEnumType(idl.IdlEnum, typename="UMAA.Common.Enumeration.LineSegmentEnumModule.LineSegmentEnumType", default="GREAT_CIRCLE"):
    GREAT_CIRCLE = auto()
    RHUMB = auto()

