"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.AnchorSpecs

"""

from ._AnchorSpecsReportType import AnchorSpecsReportType, AnchorSpecsReportTypeTopic
__all__ = [
	"AnchorSpecsReportType",
	"AnchorSpecsReportTypeTopic",
]
