"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.AnchorSpecs
  IDL file: AnchorSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.AnchorKindEnumModule
    import UMAA.Common.MaritimeEnumeration.AnchorLocationEnumModule
    import UMAA.Common.MaritimeEnumeration.AnchorRodeEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


AnchorSpecsReportTypeTopic = "UMAA::EO::AnchorSpecs::AnchorSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class AnchorSpecsReportType(idl.IdlStruct, typename="UMAA.EO.AnchorSpecs.AnchorSpecsReportType"):
    anchorDescription: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    anchorHoldingPower: 'UMAA.Common.Measurement.Mass'
    anchorHoldingPowerRatio: 'UMAA.Common.PrimitiveConstrained.Ratio'
    anchorKind: 'UMAA.Common.MaritimeEnumeration.AnchorKindEnumModule.AnchorKindEnumType'
    anchorLocation: 'UMAA.Common.MaritimeEnumeration.AnchorLocationEnumModule.AnchorLocationEnumType'
    anchorSize: 'UMAA.Common.Measurement.Mass'
    rodeLength: 'UMAA.Common.Measurement.Distance'
    rodeSize: 'UMAA.Common.Measurement.Distance'
    rodeType: 'UMAA.Common.MaritimeEnumeration.AnchorRodeEnumModule.AnchorRodeEnumType'
    rodeWorkingLoadLimit: 'UMAA.Common.Measurement.Force'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


