"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.GlobalPoseStatus
  IDL file: GlobalPoseReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.NavigationSolutionEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.PrimitiveConstrained


GlobalPoseReportTypeTopic = "UMAA::SA::GlobalPoseStatus::GlobalPoseReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalPoseReportType(idl.IdlStruct, typename="UMAA.SA.GlobalPoseStatus.GlobalPoseReportType"):
    altitude: Optional['UMAA.Common.Measurement.MSLAltitude']
    altitudeAGL: Optional['UMAA.Common.Measurement.DistanceAGL']
    altitudeASF: Optional['UMAA.Common.Measurement.DistanceASF']
    altitudeGeodetic: Optional['UMAA.Common.PrimitiveConstrained.GeodeticAltitude']
    attitude: 'UMAA.Common.Orientation.Orientation3DNEDType'
    attitudeCovariance: Optional['UMAA.Common.Measurement.CovarianceOrientationNEDType']
    course: 'UMAA.Common.Measurement.CourseTrueNorth'
    depth: Optional['UMAA.Common.Measurement.DistanceBSL']
    navigationSolution: 'UMAA.Common.MaritimeEnumeration.NavigationSolutionEnumModule.NavigationSolutionEnumType'
    position: 'UMAA.Common.Measurement.GeoPosition2D'
    positionCovariance: Optional['UMAA.Common.Measurement.CovariancePositionNEDType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


