"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalDriftControl
  IDL file: GlobalDriftExecutionStatusReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.MO.GlobalDriftState


GlobalDriftExecutionStatusReportTypeTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftExecutionStatusReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalDriftExecutionStatusReportType(idl.IdlStruct, typename="UMAA.MO.GlobalDriftControl.GlobalDriftExecutionStatusReportType"):
    distanceFromReference: 'UMAA.Common.Measurement.Distance'
    globalDriftState: 'UMAA.MO.GlobalDriftState.GlobalDriftStateType'
    timeDriftAchieved: 'UMAA.Common.Measurement.DateTime'
    timeDriftCompleted: Optional['UMAA.Common.Measurement.DateTime']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


