"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalDriftControl
  IDL file: GlobalDriftCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Distance
    import UMAA.Common.Measurement
    import UMAA.Common.Speed


GlobalDriftCommandTypeTopic = "UMAA::MO::GlobalDriftControl::GlobalDriftCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalDriftCommandType(idl.IdlStruct, typename="UMAA.MO.GlobalDriftControl.GlobalDriftCommandType"):
    driftRadius: 'UMAA.Common.Distance.DistanceRequirementType'
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    endTime: Optional['UMAA.Common.Measurement.DateTime']
    position: 'UMAA.Common.Measurement.GeoPosition2D'
    speed: 'UMAA.Common.Speed.SpeedVariantType'
    transitElevation: Optional['UMAA.Common.Measurement.ElevationVariantType']
    transitSpeed: 'UMAA.Common.Speed.SpeedVariantType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


