"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.FinsSpecs
  IDL file: FinSpecsType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class FinSpecsType(idl.IdlStruct, typename="UMAA.EO.FinsSpecs.FinSpecsType"):
    maxDeflectionRate: 'UMAA.Common.Measurement.AngleRate'
    maxNegativeDeflection: 'UMAA.Common.Measurement.Angle'
    maxPositiveDeflection: 'UMAA.Common.Measurement.Angle'
    minDeflectionRate: 'UMAA.Common.Measurement.AngleRate'
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    nominalDeflectionRate: Optional['UMAA.Common.Measurement.AngleRate']
    orientation: 'UMAA.Common.Orientation.Orientation3DPlatformType'
    position: 'UMAA.Common.Measurement.Position3DBodyXYZ'


