"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelPowerConfig
  IDL file: CommsChannelPowerConfigReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelPowerConfigReportTypeTopic = "UMAA::CO::CommsChannelPowerConfig::CommsChannelPowerConfigReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelPowerConfigReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelPowerConfig.CommsChannelPowerConfigReportType"):
    maxTransmitPowerUsage: 'UMAA.Common.Measurement.ElectricalPower'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


