"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.BITConfig
  IDL file: BITConfigCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.ContinuousTestEnumModule
    import UMAA.Common.MaritimeEnumeration.PowerOnTestEnumModule
    import UMAA.Common.Measurement


BITConfigCommandTypeTopic = "UMAA::SO::BITConfig::BITConfigCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BITConfigCommandType(idl.IdlStruct, typename="UMAA.SO.BITConfig.BITConfigCommandType"):
    continuousTestConfiguration: 'UMAA.Common.MaritimeEnumeration.ContinuousTestEnumModule.ContinuousTestEnumType'
    minTimeBetweenTests: Optional['UMAA.Common.Measurement.DurationMilliseconds']
    powerOnTestConfiguration: 'UMAA.Common.MaritimeEnumeration.PowerOnTestEnumModule.PowerOnTestEnumType'
    resourceID: 'UMAA.Common.IdentifierType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


