"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelPowerReport

"""

from ._CommsChannelPowerReportType import CommsChannelPowerReportType, CommsChannelPowerReportTypeTopic
__all__ = [
	"CommsChannelPowerReportType",
	"CommsChannelPowerReportTypeTopic",
]
