"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelPowerReport
  IDL file: CommsChannelPowerReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelPowerReportTypeTopic = "UMAA::CO::CommsChannelPowerReport::CommsChannelPowerReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelPowerReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelPowerReport.CommsChannelPowerReportType"):
    mostRecentPowerUsage: 'UMAA.Common.Measurement.ElectricalPower'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


