"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.VelocityStatus

"""

from ._VelocityReportType import VelocityReportType, VelocityReportTypeTopic
__all__ = [
	"VelocityReportType",
	"VelocityReportTypeTopic",
]
