"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.ContactFilterConfig
  IDL file: ContactFilterConfigAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


ContactFilterConfigAckReportTypeTopic = "UMAA::SA::ContactFilterConfig::ContactFilterConfigAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ContactFilterConfigAckReportType(idl.IdlStruct, typename="UMAA.SA.ContactFilterConfig.ContactFilterConfigAckReportType"):
    config: 'UMAA.SA.ContactFilterConfig.ContactFilterConfigCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


