"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.PropulsorsControl
  IDL file: PropulsorCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Angle
    import UMAA.Common.Measurement
    import UMAA.Common.Speed


PropulsorCommandTypeTopic = "UMAA::EO::PropulsorsControl::PropulsorCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class PropulsorCommandType(idl.IdlStruct, typename="UMAA.EO.PropulsorsControl.PropulsorCommandType"):
    gamma: Optional['UMAA.Common.Angle.GammaAnglePropulsorRequirementType']
    propellerPitch: Optional['UMAA.Common.Angle.PropellerPitchAnglePropulsorRequirementType']
    propulsion: 'UMAA.Common.Speed.EngineRPMSpeedRequirement'
    rho: Optional['UMAA.Common.Angle.RhoAnglePropulsorRequirementType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


