"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.MastControl
  IDL file: MastCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.MastActionEnumModule
    import UMAA.Common.Measurement


MastCommandTypeTopic = "UMAA::EO::MastControl::MastCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MastCommandType(idl.IdlStruct, typename="UMAA.EO.MastControl.MastCommandType"):
    action: 'UMAA.Common.MaritimeEnumeration.MastActionEnumModule.MastActionEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


