"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.AcousticInterferenceStatus
  IDL file: AcousticSelfNoiseInterferenceStatusType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.MaritimeEnumeration.InterferenceEnumModule
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class AcousticSelfNoiseInterferenceStatusType(idl.IdlStruct, typename="UMAA.SEM.AcousticInterferenceStatus.AcousticSelfNoiseInterferenceStatusType"):
    bandwidth: Optional['UMAA.Common.Measurement.FrequencyHertz']
    centerFrequency: Optional['UMAA.Common.Measurement.FrequencyHertz']
    duration: 'UMAA.Common.Measurement.DurationSeconds'
    time: 'UMAA.Common.Measurement.DateTime'
    type: Optional['UMAA.Common.MaritimeEnumeration.InterferenceEnumModule.InterferenceEnumType']


