"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.BITReport
  IDL file: BITReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


BITReportTypeTopic = "UMAA::SO::BITReport::BITReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BITReportType(idl.IdlStruct, typename="UMAA.SO.BITReport.BITReportType"):
    commandBITAvailable: bool
    timeOfLastBIT: Optional['UMAA.Common.Measurement.DateTime']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    resourceID: 'UMAA.Common.IdentifierType'
    annotate.key("resourceID")


