"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.COLREGSClassificationEnumModule

"""

from ._MaritimeEnumerationSets import COLREGSClassificationEnumType
__all__ = [
	"COLREGSClassificationEnumType",
]
