"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.OrientationStatus

"""

from ._OrientationReportType import OrientationReportType, OrientationReportTypeTopic
__all__ = [
	"OrientationReportType",
	"OrientationReportTypeTopic",
]
