"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.OrientationStatus
  IDL file: OrientationReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation


OrientationReportTypeTopic = "UMAA::SA::OrientationStatus::OrientationReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class OrientationReportType(idl.IdlStruct, typename="UMAA.SA.OrientationStatus.OrientationReportType"):
    attitude: 'UMAA.Common.Orientation.Orientation3DNEDType'
    attitudeCovariance: Optional['UMAA.Common.Measurement.CovarianceOrientationNEDType']
    attitudeRate: Optional['UMAA.Common.Measurement.OrientationVel3D']
    attitudeRateCovariance: Optional['UMAA.Common.Measurement.CovarianceOrientationVelocityNEDType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


