"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BallastTank
  IDL file: BallastPumpFlowRateType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class BallastPumpFlowRateTypeEnum(idl.IdlEnum, typename="UMAA.EO.BallastTank.BallastPumpFlowRateTypeEnum", default="MASSBALLASTFLOWRATE_D"):
    MASSBALLASTFLOWRATE_D = auto()
    VOLUMEBALLASTFLOWRATE_D = auto()


@annotate.final
@annotate.nested
class BallastPumpFlowRateTypeUnion(idl.IdlUnion, discriminator=BallastPumpFlowRateTypeEnum, discriminator_is_key=False, typename="UMAA.EO.BallastTank.BallastPumpFlowRateTypeUnion"):
    MassBallastFlowRateVariant: types.case[[BallastPumpFlowRateTypeEnum.MASSBALLASTFLOWRATE_D], 'UMAA.EO.BallastTank.MassBallastFlowRateType']
    VolumeBallastFlowRateVariant: types.case[[BallastPumpFlowRateTypeEnum.VOLUMEBALLASTFLOWRATE_D], 'UMAA.EO.BallastTank.VolumeBallastFlowRateType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class BallastPumpFlowRateType(idl.IdlStruct, typename="UMAA.EO.BallastTank.BallastPumpFlowRateType"):
    BallastPumpFlowRateTypeSubtypes: 'UMAA.EO.BallastTank.BallastPumpFlowRateTypeUnion'


