"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BallastTank
  IDL file: BallastTankReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


BallastTankReportTypeTopic = "UMAA::EO::BallastTank::BallastTankReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BallastTankReportType(idl.IdlStruct, typename="UMAA.EO.BallastTank.BallastTankReportType"):
    level: Optional['UMAA.Common.Measurement.VolumePercent']
    lowPressureLimit: 'UMAA.Common.Measurement.PressureKiloPascals'
    mass: Optional['UMAA.Common.Measurement.Mass']
    pressure: 'UMAA.Common.Measurement.PressureKiloPascals'
    pressureLimit: 'UMAA.Common.Measurement.PressureKiloPascals'
    trimActive: bool
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


