"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.BallastTank
  IDL file: BallastFillType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement


@annotate.final
class BallastFillTypeEnum(idl.IdlEnum, typename="UMAA.EO.BallastTank.BallastFillTypeEnum", default="LEVEL_D"):
    LEVEL_D = auto()
    BALLASTMASS_D = auto()


@annotate.final
@annotate.nested
class BallastFillTypeUnion(idl.IdlUnion, discriminator=BallastFillTypeEnum, discriminator_is_key=False, typename="UMAA.EO.BallastTank.BallastFillTypeUnion"):
    LevelVariant: types.case[[BallastFillTypeEnum.LEVEL_D], 'UMAA.Common.Measurement.LevelType']
    BallastMassVariant: types.case[[BallastFillTypeEnum.BALLASTMASS_D], 'UMAA.Common.Measurement.BallastMassType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class BallastFillType(idl.IdlStruct, typename="UMAA.EO.BallastTank.BallastFillType"):
    BallastFillTypeSubtypes: 'UMAA.EO.BallastTank.BallastFillTypeUnion'


