"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelEnvironmentReport

"""

from ._CommsChannelEnvironmentReportType import CommsChannelEnvironmentReportType, CommsChannelEnvironmentReportTypeTopic
__all__ = [
	"CommsChannelEnvironmentReportType",
	"CommsChannelEnvironmentReportTypeTopic",
]
