"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelEnvironmentReport
  IDL file: CommsChannelEnvironmentReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


CommsChannelEnvironmentReportTypeTopic = "UMAA::CO::CommsChannelEnvironmentReport::CommsChannelEnvironmentReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelEnvironmentReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelEnvironmentReport.CommsChannelEnvironmentReportType"):
    mostRecentSNR: 'UMAA.Common.PrimitiveConstrained.SignalToNoiseRatio'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


