"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ReferenceFrameOriginEnumModule

"""

from ._MaritimeEnumerationSets import ReferenceFrameOriginEnumType
__all__ = [
	"ReferenceFrameOriginEnumType",
]
