"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ReferenceFrameOriginEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ReferenceFrameOriginEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ReferenceFrameOriginEnumModule.ReferenceFrameOriginEnumType", default="BOW_WATERLINE_INTERSECTION"):
    BOW_WATERLINE_INTERSECTION = auto()
    CENTER_OF_BUOYANCY = auto()
    CENTER_OF_GRAVITY = auto()
    INS_LOCATION = auto()
    KEEL_TRANSOM_INTERSECTION = auto()

