"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Enumeration.SpecificLOIEnumModule
  IDL file: EnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class SpecificLOIEnumType(idl.IdlEnum, typename="UMAA.Common.Enumeration.SpecificLOIEnumModule.SpecificLOIEnumType", default="LOI_1"):
    LOI_1 = auto()
    LOI_2 = auto()
    LOI_3 = auto()
    LOI_4 = auto()
    LOI_5 = auto()

