"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ActiveConstraintsControl
  IDL file: ActiveConstraintsCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


ActiveConstraintsCommandTypeTopic = "UMAA::MM::ActiveConstraintsControl::ActiveConstraintsCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ActiveConstraintsCommandType(idl.IdlStruct, typename="UMAA.MM.ActiveConstraintsControl.ActiveConstraintsCommandType"):
    constraintConditionalIDs: types.sequence['UMAA.Common.Measurement.NumericGUID', 256]
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


