"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.TaskPlanExecutionStatus
  IDL file: TaskPlanExecutionReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.TaskStateEnumModule
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


TaskPlanExecutionReportTypeTopic = "UMAA::MM::TaskPlanExecutionStatus::TaskPlanExecutionReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class TaskPlanExecutionReportType(idl.IdlStruct, typename="UMAA.MM.TaskPlanExecutionStatus.TaskPlanExecutionReportType"):
    endTime: Optional['UMAA.Common.Measurement.DateTime']
    feedback: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    startTime: Optional['UMAA.Common.Measurement.DateTime']
    state: 'UMAA.Common.MaritimeEnumeration.TaskStateEnumModule.TaskStateEnumType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    missionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("missionID")
    taskID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("taskID")


