"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.BITControl
  IDL file: BITExecutionStatusReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


BITExecutionStatusReportTypeTopic = "UMAA::SO::BITControl::BITExecutionStatusReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class BITExecutionStatusReportType(idl.IdlStruct, typename="UMAA.SO.BITControl.BITExecutionStatusReportType"):
    estimatedTestCompletion: Optional['UMAA.Common.Measurement.DateTime']
    resourceID: 'UMAA.Common.IdentifierType'
    testCancelable: bool
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")


