"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.ObjectiveAssignmentReport

"""

from ._ObjectiveAssignmentReportType import ObjectiveAssignmentReportType, ObjectiveAssignmentReportTypeTopic
__all__ = [
	"ObjectiveAssignmentReportType",
	"ObjectiveAssignmentReportTypeTopic",
]
