"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalWaypointControl
  IDL file: GlobalWaypointType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Distance
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation
    import UMAA.Common.Position
    import UMAA.Common.PrimitiveConstrained
    import UMAA.Common.Speed



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GlobalWaypointType(idl.IdlStruct, typename="UMAA.MO.GlobalWaypointControl.GlobalWaypointType"):
    attitude: Optional['UMAA.Common.Orientation.Orientation3DNEDRequirement']
    elevation: Optional['UMAA.Common.Measurement.ElevationRequirementVariantType']
    name: Optional['UMAA.Common.PrimitiveConstrained.StringShortDescription']
    position: 'UMAA.Common.Position.GeoPosition2DRequirement'
    speed: 'UMAA.Common.Speed.VariableSpeedVariantType'
    trackTolerance: Optional['UMAA.Common.Distance.DistanceRequirementType']
    waypointID: 'UMAA.Common.Measurement.NumericGUID'


