"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Environment
  IDL file: WorldTransformType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class WorldTransformType(idl.IdlStruct, typename="UMAA.Common.Environment.WorldTransformType"):
    pixelSizex: 'UMAA.Common.Measurement.Distance'
    pixelSizey: 'UMAA.Common.Measurement.Distance'
    rotationx: 'UMAA.Common.Measurement.Angle'
    rotationy: 'UMAA.Common.Measurement.Angle'
    upperLeftCoordinatex: 'UMAA.Common.Measurement.Distance'
    upperLeftCoordinatey: 'UMAA.Common.Measurement.Distance'


