"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.FuelTankStatus

"""

from ._FuelTankReportType import FuelTankReportType, FuelTankReportTypeTopic
__all__ = [
	"FuelTankReportType",
	"FuelTankReportTypeTopic",
]
