"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.SpeedStatus

"""

from ._SpeedReportType import SpeedReportType, SpeedReportTypeTopic
__all__ = [
	"SpeedReportType",
	"SpeedReportTypeTopic",
]
