"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.SpeedStatus
  IDL file: SpeedReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.VehicleSpeedModeEnumModule
    import UMAA.Common.Measurement


SpeedReportTypeTopic = "UMAA::SA::SpeedStatus::SpeedReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class SpeedReportType(idl.IdlStruct, typename="UMAA.SA.SpeedStatus.SpeedReportType"):
    mode: Optional['UMAA.Common.MaritimeEnumeration.VehicleSpeedModeEnumModule.VehicleSpeedModeEnumType']
    speedOverGround: Optional['UMAA.Common.Measurement.GroundSpeed']
    speedThroughAir: Optional['UMAA.Common.Measurement.IndicatedAirspeed']
    speedThroughWater: Optional['UMAA.Common.Measurement.SpeedLocalWaterMass']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


