"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.InertialSensorOpStatusEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class InertialSensorOpStatusEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.InertialSensorOpStatusEnumModule.InertialSensorOpStatusEnumType", default="BEST_ALIGNMENT_FAILURE"):
    BEST_ALIGNMENT_FAILURE = auto()
    COARSE_BEST_ALIGNMENT = auto()
    COARSE_GPS_ALIGNMENT = auto()
    COARSE_STATIONARY_ALIGNMENT = auto()
    COARSE_TRANSFER_ALIGNMENT = auto()
    FINE_BEST_ALIGNMENT_COMPLETE = auto()
    FINE_BEST_ALIGNMENT_STARTED = auto()
    FINE_GPS_ALIGNMENT_COMPLETE = auto()
    FINE_GPS_ALIGNMENT_STARTED = auto()
    FINE_STATIONARY_ALIGNMENT_COMPLETE = auto()
    FINE_STATIONARY_ALIGNMENT_STARTED = auto()
    FINE_TRANSFER_ALIGNMENT_COMPLETE = auto()
    FINE_TRANSFER_ALIGNMENT_STARTED = auto()
    GPS_ALIGNMENT_FAILURE = auto()
    INERTIAL_SENSOR_FAILURE = auto()
    INIT = auto()
    SNAP_ALIGNMENT_COMPLETE = auto()
    SNAP_ALIGNMENT_FAILURE = auto()
    STATIONARY_ALIGNMENT_FAILURE = auto()
    TRANSFER_ALIGNMENT_FAILURE = auto()

