"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.EmitterPresetReport
  IDL file: EmitterPresetReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


EmitterPresetReportTypeTopic = "UMAA::SO::EmitterPresetReport::EmitterPresetReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EmitterPresetReportType(idl.IdlStruct, typename="UMAA.SO.EmitterPresetReport.EmitterPresetReportType"):
    endLevelID: Optional['UMAA.Common.Measurement.NumericGUID']
    endTime: Optional['UMAA.Common.Measurement.DateTime']
    isModified: bool
    levelID: 'UMAA.Common.Measurement.NumericGUID'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


