"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SEM.IlluminatorSpecs
  IDL file: IlluminatorSpecsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


IlluminatorSpecsReportTypeTopic = "UMAA::SEM::IlluminatorSpecs::IlluminatorSpecsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class IlluminatorSpecsReportType(idl.IdlStruct, typename="UMAA.SEM.IlluminatorSpecs.IlluminatorSpecsReportType"):
    beamWidthSpecs: Optional['UMAA.SEM.IlluminatorSpecs.BeamWidthSpecsType']
    name: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    supportedColor: bool
    supportedInfrared: bool
    supportedIntensityLevel: bool
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


