"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.EmitterPresetConfig
  IDL file: EmitterPresetConfigAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


EmitterPresetConfigAckReportTypeTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EmitterPresetConfigAckReportType(idl.IdlStruct, typename="UMAA.SO.EmitterPresetConfig.EmitterPresetConfigAckReportType"):
    config: 'UMAA.SO.EmitterPresetConfig.EmitterPresetConfigCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


