"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.EmitterPresetConfig
  IDL file: EmitterPresetConfigReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained


EmitterPresetConfigReportTypeTopic = "UMAA::SO::EmitterPresetConfig::EmitterPresetConfigReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EmitterPresetConfigReportType(idl.IdlStruct, typename="UMAA.SO.EmitterPresetConfig.EmitterPresetConfigReportType"):
    allowedEmitterID: types.sequence['UMAA.Common.Measurement.NumericGUID', 128]
    levelName: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'
    securedEmitterID: types.sequence['UMAA.Common.Measurement.NumericGUID', 128]
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    levelID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("levelID")


