"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.AnchorKindEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class AnchorKindEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.AnchorKindEnumModule.AnchorKindEnumType", default="COMMERCIAL_STOCKLESS"):
    COMMERCIAL_STOCKLESS = auto()
    DANFORTH = auto()
    FOUR_FLUKE = auto()
    GENERAL = auto()
    LIGHTWEIGHT = auto()
    MARK_2_LWT = auto()
    MARK_2_STOCKLESS = auto()
    MUSHROOM = auto()
    NAVY_TYPE_STOCK = auto()
    NONMAGNETIC = auto()
    STANDARD_NAVY_STOCKLESS = auto()
    TWO_FLUKE_BALANCED_FLUKE = auto()
    WEDGE_BLOCK_LWT = auto()

