"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MM.MissionPlanReport
  IDL file: MissionPlanReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.MM.BaseType
    import UMAA.MM.Constraint


MissionPlanReportTypeTopic = "UMAA::MM::MissionPlanReport::MissionPlanReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanReportType(idl.IdlStruct, typename="UMAA.MM.MissionPlanReport.MissionPlanReportType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    constraintsSetMetadata: 'UMAA.Common.LargeSetMetadata'
    missionPlanSetMetadata: 'UMAA.Common.LargeSetMetadata'

MissionPlanReportTypeConstraintsSetElementTopic = "UMAA::MM::MissionPlanReport::MissionPlanReportTypeConstraintsSetElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanReportTypeConstraintsSetElement(idl.IdlStruct, typename="UMAA.MM.MissionPlanReport.MissionPlanReportTypeConstraintsSetElement"):
    element: 'UMAA.MM.Constraint.ConstraintType'
    setID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("setID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'

MissionPlanReportTypeMissionPlanSetElementTopic = "UMAA::MM::MissionPlanReport::MissionPlanReportTypeMissionPlanSetElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MissionPlanReportTypeMissionPlanSetElement(idl.IdlStruct, typename="UMAA.MM.MissionPlanReport.MissionPlanReportTypeMissionPlanSetElement"):
    element: 'UMAA.MM.BaseType.MissionPlanType'
    setID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("setID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'


