"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WaterCharacteristicsStatus

"""

from ._WaterCharacteristicsReportType import WaterCharacteristicsReportType, WaterCharacteristicsReportTypeTopic
__all__ = [
	"WaterCharacteristicsReportType",
	"WaterCharacteristicsReportTypeTopic",
]
