"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WaterCharacteristicsStatus
  IDL file: WaterCharacteristicsReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


WaterCharacteristicsReportTypeTopic = "UMAA::SA::WaterCharacteristicsStatus::WaterCharacteristicsReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class WaterCharacteristicsReportType(idl.IdlStruct, typename="UMAA.SA.WaterCharacteristicsStatus.WaterCharacteristicsReportType"):
    conductivity: Optional['UMAA.Common.Measurement.Conductivity']
    density: Optional['UMAA.Common.Measurement.Density']
    depth: 'UMAA.Common.Measurement.DistanceBSL'
    pressure: Optional['UMAA.Common.Measurement.PressurePascals']
    salinity: Optional['UMAA.Common.Measurement.Salinity']
    soundVelocity: Optional['UMAA.Common.Measurement.Speed']
    temperature: Optional['UMAA.Common.Measurement.Temperature']
    turbidity: Optional['UMAA.Common.Measurement.Turbidity']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


