"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class ObjectiveExecutorStateEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.ObjectiveExecutorStateEnumModule.ObjectiveExecutorStateEnumType", default="CANCELED"):
    CANCELED = auto()
    CANCELING = auto()
    COMPLETED = auto()
    EXECUTING = auto()
    FAILED = auto()
    MODIFYING = auto()
    PAUSED = auto()
    PAUSING = auto()
    QUEUED = auto()
    RESUMING = auto()

