"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.LandmarkEnumModule

"""

from ._MaritimeEnumerationSets import LandmarkEnumType
__all__ = [
	"LandmarkEnumType",
]
