"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.LandmarkEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class LandmarkEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.LandmarkEnumModule.LandmarkEnumType", default="CLUSTER_OBJECT"):
    CLUSTER_OBJECT = auto()
    LARGE_OBJECT = auto()
    MARKED = auto()
    TERRAIN = auto()

