"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelConfig
  IDL file: CommsChannelConfigReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.CO.CommsChannel
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelConfigReportTypeTopic = "UMAA::CO::CommsChannelConfig::CommsChannelConfigReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelConfigReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelConfig.CommsChannelConfigReportType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    messageConfigsSetMetadata: 'UMAA.Common.LargeSetMetadata'

CommsChannelConfigReportTypeMessageConfigsSetElementTopic = "UMAA::CO::CommsChannelConfig::CommsChannelConfigReportTypeMessageConfigsSetElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelConfigReportTypeMessageConfigsSetElement(idl.IdlStruct, typename="UMAA.CO.CommsChannelConfig.CommsChannelConfigReportTypeMessageConfigsSetElement"):
    element: 'UMAA.CO.CommsChannel.CommsChannelMessageConfigType'
    setID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("setID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'


