"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelConfig
  IDL file: CommsChannelAddMessageConfigAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelAddMessageConfigAckReportTypeTopic = "UMAA::CO::CommsChannelConfig::CommsChannelAddMessageConfigAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelAddMessageConfigAckReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelConfig.CommsChannelAddMessageConfigAckReportType"):
    config: 'UMAA.CO.CommsChannelConfig.CommsChannelAddMessageConfigCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


