"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelConfig
  IDL file: CommsChannelDeleteMessageConfigAckReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


CommsChannelDeleteMessageConfigAckReportTypeTopic = "UMAA::CO::CommsChannelConfig::CommsChannelDeleteMessageConfigAckReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class CommsChannelDeleteMessageConfigAckReportType(idl.IdlStruct, typename="UMAA.CO.CommsChannelConfig.CommsChannelDeleteMessageConfigAckReportType"):
    config: 'UMAA.CO.CommsChannelConfig.CommsChannelDeleteMessageConfigCommandType'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


