"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.WaterZoneKindEnumModule

"""

from ._MaritimeEnumerationSets import WaterZoneKindEnumType
__all__ = [
	"WaterZoneKindEnumType",
]
