"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class TrackIdentityEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.TrackIdentityEnumModule.TrackIdentityEnumType", default="ASSUMED_FRIEND"):
    ASSUMED_FRIEND = auto()
    FAKER = auto()
    FRIEND = auto()
    HOSTILE = auto()
    JOKER = auto()
    NEUTRAL = auto()
    PENDING = auto()
    SUSPECT = auto()
    UNKNOWN = auto()

