"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceAllocation
  IDL file: ResourceAllocationConfigReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


ResourceAllocationConfigReportTypeTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationConfigReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ResourceAllocationConfigReportType(idl.IdlStruct, typename="UMAA.SO.ResourceAllocation.ResourceAllocationConfigReportType"):
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    resourcesSetMetadata: 'UMAA.Common.LargeSetMetadata'

ResourceAllocationConfigReportTypeResourcesSetElementTopic = "UMAA::SO::ResourceAllocation::ResourceAllocationConfigReportTypeResourcesSetElement"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ResourceAllocationConfigReportTypeResourcesSetElement(idl.IdlStruct, typename="UMAA.SO.ResourceAllocation.ResourceAllocationConfigReportTypeResourcesSetElement"):
    element: 'UMAA.SO.ResourceAllocation.ResourceAllocationDefinitionType'
    setID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("setID")
    elementID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("elementID")
    elementTimestamp: 'UMAA.Common.Measurement.DateTime'


