"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.ResourceAllocation
  IDL file: ResourceAllocationPriorityInfo.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class ResourceAllocationPriorityInfo(idl.IdlStruct, typename="UMAA.SO.ResourceAllocation.ResourceAllocationPriorityInfo"):
    priorities: types.sequence['UMAA.Common.IdentifierType', 64]
    resourceID: 'UMAA.Common.IdentifierType'


