"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.LandmarkReport
  IDL file: LandmarkReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.MaritimeEnumeration.LandmarkEnumModule
    import UMAA.Common.Measurement


LandmarkReportTypeTopic = "UMAA::SA::LandmarkReport::LandmarkReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class LandmarkReportType(idl.IdlStruct, typename="UMAA.SA.LandmarkReport.LandmarkReportType"):
    depth: 'UMAA.Common.Measurement.DistanceBSL'
    landmarkType: Optional['UMAA.Common.MaritimeEnumeration.LandmarkEnumModule.LandmarkEnumType']
    location: 'UMAA.Common.Measurement.GeoPosition2D'
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    landmarkID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("landmarkID")


