"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.Filter
  IDL file: DecimateStructureFilterType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class DecimateStructureFilterType(idl.IdlStruct, typename="UMAA.CO.Filter.DecimateStructureFilterType"):
    setSendMostRecent: bool
    waitTime: 'UMAA.Common.Measurement.DurationSeconds'


