"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.EO.EngineStatus
  IDL file: EngineReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Enumeration.OnOffStatusEnumModule
    import UMAA.Common.MaritimeEnumeration.IgnitionStateEnumModule
    import UMAA.Common.Measurement


EngineReportTypeTopic = "UMAA::EO::EngineStatus::EngineReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class EngineReportType(idl.IdlStruct, typename="UMAA.EO.EngineStatus.EngineReportType"):
    coolantLevel: Optional['UMAA.Common.Measurement.VolumePercent']
    coolantPressure: Optional['UMAA.Common.Measurement.PressureKiloPascals']
    coolantTemp: Optional['UMAA.Common.Measurement.Temperature']
    engineTemp: Optional['UMAA.Common.Measurement.Temperature']
    exhaustTemp: Optional['UMAA.Common.Measurement.Temperature']
    glowPlugIndicator: Optional[bool]
    glowPlugState: Optional['UMAA.Common.Enumeration.OnOffStatusEnumModule.OnOffStatusEnumType']
    glowPlugTemp: Optional['UMAA.Common.Measurement.Temperature']
    glowPlugTimeRemaining: Optional['UMAA.Common.Measurement.DurationSeconds']
    hours: Optional['UMAA.Common.Measurement.DurationHours']
    manifoldAirTemp: Optional['UMAA.Common.Measurement.Temperature']
    manifoldPressure: Optional['UMAA.Common.Measurement.PressureKiloPascals']
    oilLevel: Optional['UMAA.Common.Measurement.VolumePercent']
    oilPressure: Optional['UMAA.Common.Measurement.PressureKiloPascals']
    oilTemp: Optional['UMAA.Common.Measurement.Temperature']
    percentOilPressure: Optional['UMAA.Common.Measurement.PressurePercent']
    RPM: Optional['UMAA.Common.Measurement.EngineSpeed']
    state: 'UMAA.Common.MaritimeEnumeration.IgnitionStateEnumModule.IgnitionStateEnumType'
    throttle: Optional['UMAA.Common.Measurement.Effort']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


