"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannelDataEncodingReport

"""

from ._CommsChannelDataEncodingReportType import CommsChannelDataEncodingReportType, CommsChannelDataEncodingReportTypeTopic
__all__ = [
	"CommsChannelDataEncodingReportType",
	"CommsChannelDataEncodingReportTypeTopic",
]
