"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.GPSConstellationEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class GPSConstellationEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.GPSConstellationEnumModule.GPSConstellationEnumType", default="BEIDOU"):
    BEIDOU = auto()
    GALILEO = auto()
    GLONASS = auto()
    GPS = auto()
    IRNSS = auto()
    QZSS = auto()
    SBAS = auto()
    UNKNOWN = auto()

