"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.AnchorRodeEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class AnchorRodeEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.AnchorRodeEnumModule.AnchorRodeEnumType", default="CHAIN"):
    CHAIN = auto()
    ROPE = auto()

