"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.CoordinationSituationalSignalEnumModule

"""

from ._MaritimeEnumerationSets import CoordinationSituationalSignalEnumType
__all__ = [
	"CoordinationSituationalSignalEnumType",
]
