"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.MaritimeEnumeration.CoordinationSituationalSignalEnumModule
  IDL file: MaritimeEnumerationSets.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class CoordinationSituationalSignalEnumType(idl.IdlEnum, typename="UMAA.Common.MaritimeEnumeration.CoordinationSituationalSignalEnumModule.CoordinationSituationalSignalEnumType", default="AGREE_TO_BE_OVERTAKEN"):
    AGREE_TO_BE_OVERTAKEN = auto()
    ALTERING_COURSE_TO_PORT = auto()
    ALTERING_COURSE_TO_STARBOARD = auto()
    BLIND_BEND_SIGNAL = auto()
    DANGER_SIGNAL = auto()
    IN_DISTRESS_NEED_ASSISTANCE = auto()
    NONE = auto()
    OPERATING_ASTERN_PROPULSION = auto()
    TO_OVERTAKE_LEAVE_VESSEL_TO_PORT = auto()
    TO_OVERTAKE_LEAVE_VESSEL_TO_STARBOARD = auto()
    VESSEL_LEAVING_DOCK = auto()
    VISIBILITY_RESTRICTED_VEHICLE_STOPPED = auto()
    VISIBILITY_RESTRICTED_VEHICLE_UNDERWAY = auto()

