"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.CO.CommsChannel
  IDL file: CommsChannelMessageType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement
    import UMAA.Common.PrimitiveConstrained



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class CommsChannelMessageType(idl.IdlStruct, typename="UMAA.CO.CommsChannel.CommsChannelMessageType"):
    messageID: 'UMAA.Common.Measurement.NumericGUID'
    messageSize: 'UMAA.Common.Measurement.SizeBytes'
    messageTimeStamp: 'UMAA.Common.Measurement.DateTime'
    messageType: 'UMAA.Common.PrimitiveConstrained.StringShortDescription'


