"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Time

"""

from ._DateTimeRequirementType import DateTimeRequirementType
from ._DateTimeToleranceType import DateTimeToleranceType
__all__ = [
	"DateTimeRequirementType",
	"DateTimeToleranceType",
]
