"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.Common.Time
  IDL file: DateTimeRequirementType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common.Measurement



@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class DateTimeRequirementType(idl.IdlStruct, typename="UMAA.Common.Time.DateTimeRequirementType"):
    time: 'UMAA.Common.Measurement.DateTime'
    timeTolerance: Optional['UMAA.Common.Time.DateTimeToleranceType']


