"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SO.MemoryStatus
  IDL file: MemoryReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


MemoryReportTypeTopic = "UMAA::SO::MemoryStatus::MemoryReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class MemoryReportType(idl.IdlStruct, typename="UMAA.SO.MemoryStatus.MemoryReportType"):
    bufferedRam: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    freeMemory: 'UMAA.Common.Measurement.SizeLargeBytes'
    freeSwap: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    sharedMemory: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    totalMemory: 'UMAA.Common.Measurement.SizeLargeBytes'
    totalSwap: Optional['UMAA.Common.Measurement.SizeLargeBytes']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


