"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalHoverState
  IDL file: GlobalHoverStateType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class GlobalHoverStateTypeEnum(idl.IdlEnum, typename="UMAA.MO.GlobalHoverState.GlobalHoverStateTypeEnum", default="GLOBALTRANSITHOVER_D"):
    GLOBALTRANSITHOVER_D = auto()
    GLOBALHOVERINGHOVER_D = auto()


@annotate.final
@annotate.nested
class GlobalHoverStateTypeUnion(idl.IdlUnion, discriminator=GlobalHoverStateTypeEnum, discriminator_is_key=False, typename="UMAA.MO.GlobalHoverState.GlobalHoverStateTypeUnion"):
    GlobalTransitHoverVariant: types.case[[GlobalHoverStateTypeEnum.GLOBALTRANSITHOVER_D], 'UMAA.MO.GlobalHoverState.GlobalTransitHoverType']
    GlobalHoveringHoverVariant: types.case[[GlobalHoverStateTypeEnum.GLOBALHOVERINGHOVER_D], 'UMAA.MO.GlobalHoverState.GlobalHoveringHoverType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GlobalHoverStateType(idl.IdlStruct, typename="UMAA.MO.GlobalHoverState.GlobalHoverStateType"):
    GlobalHoverStateTypeSubtypes: 'UMAA.MO.GlobalHoverState.GlobalHoverStateTypeUnion'


