"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.GlobalPoseConfig
  IDL file: GlobalPoseConfigCommandType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement
    import UMAA.Common.Orientation


GlobalPoseConfigCommandTypeTopic = "UMAA::SA::GlobalPoseConfig::GlobalPoseConfigCommandType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class GlobalPoseConfigCommandType(idl.IdlStruct, typename="UMAA.SA.GlobalPoseConfig.GlobalPoseConfigCommandType"):
    attitude: 'UMAA.Common.Orientation.Orientation3DNEDRequirement'
    attitudeCovariance: Optional['UMAA.Common.Measurement.CovarianceOrientationNEDType']
    elevation: 'UMAA.Common.Measurement.ElevationVariantType'
    position: 'UMAA.Common.Measurement.GeoPosition2D'
    positionCovariance: Optional['UMAA.Common.Measurement.CovariancePositionNEDType']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")
    sessionID: 'UMAA.Common.Measurement.NumericGUID'
    annotate.key("sessionID")
    destination: 'UMAA.Common.IdentifierType'
    annotate.key("destination")


