"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.MO.GlobalDriftState
  IDL file: GlobalDriftStateType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

@annotate.final
class GlobalDriftStateTypeEnum(idl.IdlEnum, typename="UMAA.MO.GlobalDriftState.GlobalDriftStateTypeEnum", default="GLOBALTRANSITDRIFT_D"):
    GLOBALTRANSITDRIFT_D = auto()
    GLOBALREGIONDRIFT_D = auto()


@annotate.final
@annotate.nested
class GlobalDriftStateTypeUnion(idl.IdlUnion, discriminator=GlobalDriftStateTypeEnum, discriminator_is_key=False, typename="UMAA.MO.GlobalDriftState.GlobalDriftStateTypeUnion"):
    GlobalTransitDriftVariant: types.case[[GlobalDriftStateTypeEnum.GLOBALTRANSITDRIFT_D], 'UMAA.MO.GlobalDriftState.GlobalTransitDriftType']
    GlobalRegionDriftVariant: types.case[[GlobalDriftStateTypeEnum.GLOBALREGIONDRIFT_D], 'UMAA.MO.GlobalDriftState.GlobalRegionDriftType']


@dataclass
@annotate.final
@annotate.autoid("sequential")
@annotate.nested
class GlobalDriftStateType(idl.IdlStruct, typename="UMAA.MO.GlobalDriftState.GlobalDriftStateType"):
    GlobalDriftStateTypeSubtypes: 'UMAA.MO.GlobalDriftState.GlobalDriftStateTypeUnion'


