"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: UMAA.SA.WindStatus
  IDL file: WindReportType.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import UMAA

if TYPE_CHECKING:
    import UMAA.Common
    import UMAA.Common.Measurement


WindReportTypeTopic = "UMAA::SA::WindStatus::WindReportType"

@dataclass
@annotate.final
@annotate.autoid("sequential")
class WindReportType(idl.IdlStruct, typename="UMAA.SA.WindStatus.WindReportType"):
    relativeAverageDirection: Optional['UMAA.Common.Measurement.RelativeAngle']
    relativeAverageSpeed: Optional['UMAA.Common.Measurement.Speed']
    relativeInstantaneousDirection: Optional['UMAA.Common.Measurement.RelativeAngle']
    relativeInstantaneousSpeed: Optional['UMAA.Common.Measurement.Speed']
    relativeMaximumDirection: Optional['UMAA.Common.Measurement.RelativeAngle']
    relativeMaximumSpeed: Optional['UMAA.Common.Measurement.Speed']
    relativeMinimumDirection: Optional['UMAA.Common.Measurement.RelativeAngle']
    relativeMinimumSpeed: Optional['UMAA.Common.Measurement.Speed']
    straightDeckCrossSpeed: Optional['UMAA.Common.Measurement.Speed']
    straightDeckHeadSpeed: Optional['UMAA.Common.Measurement.Speed']
    trueAverageDirection: Optional['UMAA.Common.Measurement.AzimuthTrueNorthAngle']
    trueAverageSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    trueInstantaneousDirection: Optional['UMAA.Common.Measurement.AzimuthTrueNorthAngle']
    trueInstantaneousSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    trueMaximumDirection: Optional['UMAA.Common.Measurement.AzimuthTrueNorthAngle']
    trueMaximumSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    trueMinimumDirection: Optional['UMAA.Common.Measurement.AzimuthTrueNorthAngle']
    trueMinimumSpeed: Optional['UMAA.Common.Measurement.GroundSpeed']
    timeStamp: 'UMAA.Common.Measurement.DateTime'
    source: 'UMAA.Common.IdentifierType'
    annotate.key("source")


